### ISSUE TITLE
FFU login fejler

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#1029]
Jeg har logget på som anonym bruger på DK-810010 med succes.
Men logger jeg på som en gyldig låner fejler login med

> FEJL ved hent af token: { "code": 400, "error": "invalid_grant", "error_description": "User credentials are invalid" }

Adgangskoden hos fx. Rex.kb.dk skal være **alfanumerisk** og på mindst 8 tegn.

Har meldt samme problem ind på REQ0034462. Dette skulle være rettet for Bibliotek.dk

**Comment by vibjerg** [comment]
Jeg har som bruger på det kgl. bibliotek både en pincode og et password. Jeg kan via Borchk kun  logge ind via min pincode, og jeg kan derfor også kun bruge det på bibliotek.dk, login.bib.dk og serviceprovideren.

**Comment by DDBdrift** [comment]
Jeg tror, at problemet i virkeligheden ligger i KBs vejledning:
"Pinkoden skal bestå af 4 tal. Den bruges ved selvbetjeningsautomaterne KB/KUB/RUB og ved kopimaskiner på KB/KUB"
og
"Adgangskode skal bestå af min. 8 tegn og indeholde både tal og bogstaver. Den bruges når du logger på webservices."
Det ville jeg tolke som at det er adgangskoden, der anvendes på Bibliotek.dk - og pinkoden kun anvendes på automater på KB.
Har skrevet til KB om denne forvirring.
