### ISSUE TITLE
Deploy setup

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#12]
Jeg talte med Kira i fredags omkring deploy-setup, og det, der så vidt jeg forstod skal gøres ved repositoriet er at:

- [x] sikre at DBC-integrationsserver har rettigheder til repositoriet, 
- [x] oprette dmz og stable branches. 

@KiraH: det var ikke andet vel?

**Comment by KiraH** [comment]
Nej, der skal ikke gøres andet ved repositoriet.

Fra: RasmusErik Voel Jensen [mailto:notifications@github.com]
Sendt: 22. februar 2016 07:24
Til: DBCDK/serviceprovider
Cc: Kira Høegh
Emne: [serviceprovider] Deploy setup (#12)


Jeg talte med Kira i fredags omkring deploy-setup, og det, der så vidt jeg forstod skal gøres ved repositoriet er at:

  *   sikre at DBC-integrationsserver har rettigheder til repositoriet,
  *   oprette dmz og stable branches.

@KiraH<https://github.com/KiraH>: det var ikke andet vel?

**Comment by rasmuserik** [comment]
ok, - så har jeg oprettet dmz og stable branch.

Jeg har ikke rettigheder til at give integrationsserver rettigheder til repositoriet (og er ej sikker på om den allerede har det, og hvad den hedder), så dette overlader jeg til andre.

**Comment by KiraH** [comment]
Super :) 

Jeg har heller ikke rettigheder til dette repo, men der er en gruppe der hedder UX Team som integrationsserveren er medlem af, så hvis man giver denne gruppe rettigheder så har både ux teamet og integrationsserveren fået rettigheder til repoet.
