### ISSUE TITLE
increase version to 1.0.0

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#122]
since the api-version currently depends on the project version, we should up the version to 1.0.0, so that people can start hitting the /v1 endpoint, instead of /v0.

**Comment by adamtulinius** [comment]
Re-open PR #123 and merge it, when ready.

**Comment by rasmuserik** [comment]
NB: we should also update urls in guide/doc/browser-api-client, etc. which currently points to /v0/
(grep/replace, or just reassign this issue to me, when version is increased)
