### ISSUE TITLE
/work endpoint

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#124]
- [x] Specifikation klar
- [x] working, unfinished implementation
- [x] Implementation færdig
- [ ] Tests (ave)
- [ ] Kører i drift
- [ ] Performance test
- [ ] Erklæret færdig (US/RJE/ANM/AVE)

We are implementing the `/work` endpoint.

## Notes about getting the data

We get the following data:

- BriefDisplay (from getObject, `bd` in `work-context.ld`)
- DKABM (from getObject, `dc`, `dkdcplus`, `dcterms`, `ac`  in `work-context.ld`)
- Relations (from getObject, `dbcaddi`, `dbcbib` in `work-context.ld`)
- CoverImage (moreinfo, not in default fields, `mi` in  in `work-context.ld`)
- collection (from opensearch, not default, `os` in `work-context.ld`)

The request to get Briefdisplay, DKABM and Relations given an identifier is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://oss.dbc.dk/ns/opensearch">
  <SOAP-ENV:Body>
    <ns1:getObjectRequest>
      <ns1:agency>100200</ns1:agency>
      <ns1:profile>test</ns1:profile>
      <ns1:identifier>870970-basis:24168638</ns1:identifier>
      <ns1:objectFormat>briefDisplay</ns1:objectFormat> <!-- drop this if no field from briefdisplay is needed-->
      <ns1:objectFormat>dkabm</ns1:objectFormat> <!-- drop this if no fields from dkabm is needed -->
      <ns1:relationData>uri</ns1:relationData> <!-- drop this if no fields from relations is needed -->
    </ns1:getObjectRequest>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
Omit the formats/data not needed.

If we need the collection, we get it from opensearch:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://oss.dbc.dk/ns/opensearch">
  <SOAP-ENV:Body>
    <ns1:searchRequest>
      <ns1:query>rec.id=870970-basis:24168638</ns1:query>
      <ns1:agency>100200</ns1:agency>
      <ns1:profile>test</ns1:profile>
      <ns1:start>1</ns1:start>
      <ns1:stepValue>1</ns1:stepValue>
      <ns1:collectionType>work-1</ns1:collectionType>
      <ns1:allObjects>1</ns1:allObjects>
    </ns1:searchRequest>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Notice: it looks as if it is much faster to call getobject and opensearch separately, rather than getting all the info through a single call to opensearch.

If we need the cover images, we can get them from moreinfo.

## Notes about processing the data

The desired keys in the result object for the bibliographical data is specified in https://raw.githubusercontent.com/DBCDK/serviceprovider/master/doc/work-context.jsonld

A small percentage bibliographic data has errors, so when looking up the json-key for an xml-tag, do the comparison case insensitive and ignore special symbols. If the type for a creator/contributor does not match the types in `work-context.jsonld`, just give it the `dkdcplus:oth` type instead.

**Comment by jacobandresen** [comment]
Looks like "collection" works for a subset of data right now for the /work endpoint.

this currently works: { pids: [ '870970-basis:22629344' ],
  fields: 
   [ 'collection',
     'coverUrlFull',
     'dcTitle',
     'subjectDBCF',
     'creator',
     'abstract',
     'workType',
     'date' ] }    

but this doesn't 

{ pids: [ '775100-katalog:42946400' ],
  fields: 
   [ 'collection',
     'coverUrlFull',
     'dcTitle',
     'subjectDBCF',
     'creator',
     'abstract',
     'workType',
     'date' ] }
