### ISSUE TITLE
/facets endpoint

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#127]
- [x] Specifikation klar
- [x] working, unfinished implementation
- [x] Implementation færdig
- [ ] Tests (ave)
- [ ] Kører i drift
- [ ] Performance test
- [ ] Erklæret færdig (US/RJE/ANM/AVE)

**Comment by adamtulinius** [comment]
Should probably use the regular URL-driven api of opensearch, instead of SOAP.

**Comment by rasmuserik** [comment]
We use soap, instead of url-driven api, as SendRequests apparently does not support several query parameters with same name, which we need.
