### ISSUE TITLE
/search endpoint

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#133]
- [x] Specifikation klar
- [x] working, unfinished implementation
- [x] Implementation færdig
- [ ] Tests (ave)
- [ ] Kører i drift
- [ ] Performance test
- [ ] Erklæret færdig (US/RJE/ANM/AVE)

Note: to begin with we always use work-1. Later version of the api might also have an option to switch between manifest and work-1.

If fields are omitted it will return fields from DKABM,

**Comment by rasmuserik** [comment]
Current version is partially working, - and also includes code to convert object from opensearch to json-ld, which is also usable in `/work`. This needs to be refactored / moved into a separate file though.

**Comment by adamtulinius** [comment]
Should probably use the regular URL-driven api of opensearch, instead of SOAP.

**Comment by rasmuserik** [comment]
We use soap, instead of url-driven api, as SendRequests apparently does not support several query parameters with same name, which we need.
