### ISSUE TITLE
Should each file have license boilerplate text?

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#165]

**Comment by cboesgaard** [comment]
AVE henviste til FAF. Jacob siger:
http://www.gnu.org/licenses/why-affero-gpl.en.html
Og:
http://wiki.dbc.dk/bin/view/Udvikler/OpenSourcePraksis

**Comment by cboesgaard** [comment]
LICENSE.txt has been added with AGPL (se #350). But the question is still whether each source file should be boilerplated. ANM should be asked. But really an 1.1 thing.

See:
http://www.ifosslr.org/ifosslr/article/view/47/102

**Comment by BettinaAndersen** [comment]
Relevans overskrevet
