### ISSUE TITLE
access_token should be usable as a parameter in requests.

### ISSUE THREAD

**Issue by damkjaer** [DBCDK/serviceprovider#177]
The Token from smaug should be usable as a parameter 'access_token' in all requests to the serviceprovider.

**Comment by adamtulinius** [comment]
Do we accept `access_token` as query parameter in a GET request?
As a query parameter in a POST request?
As parameter in the json-body that is sent as a post request? 
All of the above?

What should we do if a client sends a token in multiple ways? Prioritize them in some random way, or fail with a "multiple tokens sent"-error of some sorts (my favourite).

**Comment by damkjaer** [comment]
Isn't this a general problem? Dos this not apply to all of our parameters?
We should handle this the same way we would handle all other parameters. IMHO this is all of the above.

**Comment by adamtulinius** [comment]
This is the only parameter that is related to security, so i think it deserves special consideration.

I'll implement this feature during the week, probably with the solution to fail if the request contains multiple access tokens.
