### ISSUE TITLE
Make call-method (or similar) handle BaseSoap-requests too.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#209]
This is necessary if we want to have correct timings, and also in order to mock for testing.

Problem with context.call mentioned in #208.

**Comment by rasmuserik** [comment]
Probably split call out into several methods (call-transformer, call-basesoap(needed in neoCoverImage), call-soap, call-query) which can be called separately if needed (and also with url not directly in config, as needed in neosuggest).

**Comment by cboesgaard** [comment]
Sound like a good solution,
