### ISSUE TITLE
Fix configuration and eliminate dependency on "secret" dbc module

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#21]
We currently have a dependency on a @dbcdk node module used for configuration.

This should be eliminated and replaced with full configuration by environment (and no defaults) integrated in this repo.

**Comment by rasmuserik** [comment]
Removed dependency on secret module in #32.
Full configuration in environment (no defaults) still needs to be done.

**Comment by adamtulinius** [comment]
Since the module is gone, we can close this.
