### ISSUE TITLE
Update spec based on meeting today

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#238]
- [x] /user `registered` not applicable
- [x] /order cannot change library/expires
- [x] /order /user no expiration information available
- [x] /user only title+creator (no pid)
- [x] /user typo: loans/orders should be list
- [x] /availability only ill/agency level

- [ ] /user - do we have arrival information??

- [x]  type"-parameter seems to be required, but is marked optional in the spec.

**Comment by adamtulinius** [comment]
Related (and probably not warranting its own issue): suggests's "type"-parameter seems to be required, but is marked optional in the spec.
