### ISSUE TITLE
coverDataUrlXXX

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#261]

**Comment by damkjaer** [comment]
Just to make sure. I believe we agreed, this is not part of v1.

**Comment by rasmuserik** [comment]
yes, this is [low priority](https://github.com/DBCDK/serviceprovider/blob/master/doc/api-design.md#priorities-of-features), - I just added/self-assigned it here, as a carrot / motivation - as it is one of the things that can be fun/quick to implement in between some of the other bugs, so I'll only do it when there is no high priority issues, and I need a small "break".
