### ISSUE TITLE
context should wrap "requestPromise" for timing and test-mock

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#284]
used in recommend transformer

**Comment by cboesgaard** [comment]
Related: we use the request module in three different ways: (1) directly (in caller.js) (2) using sendRequest/HttpClient.js (3) using requestPromise.js. We should only use requestPromise.js (maybe fix that if it's not good enough).

**Comment by rasmuserik** [comment]
Instead of using requestPromise/HTTPClient/request, we now only wrap only in caller.js.
