### ISSUE TITLE
Relax linter until release

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#289]
There is no reason to follow the eslint nitpicking while we are coding away -- but we should deliver the code to UX following their guideline/lint-rules (some might be up for discussion!).

**Comment by cboesgaard** [comment]
These are the exceptions mentioned in the code now:
2 eslint-disable-line dot-notation
2 eslint-disable-line no-console
2 eslint-disable-line no-new
2 eslint-disable-line no-undef
2 eslint-disable-line  no-unused-expressions
3 eslint-disable-line no-undefined
4 eslint-disable-line no-unused-expressions
5 eslint-disable-line no-loop-func
6 eslint-disable-line indent
7 eslint-disable-line guard-for-in
7 eslint-disable-line max-len
13 eslint-disable-line no-process-env
14 eslint-disable-line brace-style
24 eslint-disable-line
73 eslint-disable-line no-unused-vars

**Comment by cboesgaard** [comment]
XP "fixes" must be commented with XP, e.g.:
 // XP "no-trailing-spaces": 2,

 // XP
 // "brace-style": [

**Comment by kkdbc** [comment]
uaktuel
