### ISSUE TITLE
/recommend spec: naming of parameters + optional "recommend"-type

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#291]
In the backend webservice the parameters for pid-lists are named: like, dislike, known, discard.

We want consistent naming in the SP API (right now it is likes/dislikes/known/discard). 

Also, the "recommend" parameter should be optional.

**Comment by rasmuserik** [comment]
I have changed the names in the spec to like/dislike, in pull request #298 

The recommend parameters (as well as the others) are already optional.
(are like required or is it possible to get recommends having only disliked items?)

I have not updated the naming in the code, as it would probably conflict with your work on it,
and thus just reassigned this issue, for propagating the naming into the code.
