### ISSUE TITLE
/libraries: various NCIP-parameters not included in response

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#304]
ncipLookupUser, ncipRenewOrder etc. which are part of the findLibraryResponse from Open Agency is not returned.

**Comment by rasmuserik** [comment]
The current implementation filters away `ncip*` under the assumption that some of this information was not intended to be public (ie. `ncipPassword`), and the assumption that the end-user of the API would not use ncip directly. Is this a wrong assumption?

**Comment by ave-dbc** [comment]
will investigate - and I have asked @cboesgaard to add me to https://github.com/DBCDK/serviceprovider/network/members

**Comment by ave-dbc** [comment]
if ncipPassword is present in Open Agency's database (VIP), it should be available to the requester. But I think that the assumption that NCIP-info is not relevant in the service provider is correct. Ideally, the sentence "The possible result fields are the same as those returned from DBCs openagency service" in spec.yaml should be adjusted. This is just a minor detail. 

At a later point it might be useful to see if there are more data elements that could be removed from the libraries-response.
