### ISSUE TITLE
/libraries spec: misleading examples request

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#306]
request: { "fields": ["branchId", "city", "longitude", "latitude"]}
request: { "branchIds": ["700401", "710104"], "fields": ["branchId", "city", "longitude", "latitude"]}

Response cannot be filtered on the fields longitude, latitude (as they are subparameters of geolocation)

**Comment by rasmuserik** [comment]
Thanks, yup, that is a bug, I'll look at it tomorrow :)
