### ISSUE TITLE
/news spec: fields not listed under properties

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#307]

**Comment by rasmuserik** [comment]
As fields is applicable to every endpoint, it is only specified in the spec.yaml if there are special notes, and should be added automatically to the swagger-file. I'll check tomorrow if it is in the swaggerfile, and if not look into that as an issue.

**Comment by rasmuserik** [comment]
A general field parameter is added to the documentation automatically, if absent from the spec. Better specification/documentation of default fields will be addressed in #308. If you look at the api documentation on openplatform.dbc.dk, or the generated swagger.json (not spec.json) it is already there automagically.
