### ISSUE TITLE
/availability: returns error

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#309]
"pid": "870970-basis:22503030"

Response:
{
  "statusCode": 500,
  "error": "TypeError: Cannot read property 'authgroupid' of undefined"
}

I assume that it is an autentication-error of some sort, but eg. user and renew works ok.

**Comment by rasmuserik** [comment]
Works fine locally, assuming it is something with the production setup, and will be fixed with #311

**Comment by ave-dbc** [comment]
Reopening this as it is failing on http://platform-i01:8080/v0/availability and I cannot see how it's related to #311 

Created test case availability_01_ave

Response:
{"statusCode":500,"error":"TypeError: Cannot read property 'authgroupid' of undefined"}

REQUEST='
{ 
	"pid": "870970-basis:51353242",
	"pretty": true
}'

**Comment by damkjaer** [comment]
Error found. It seems like the openholdingstatus block is missing from the context on platform-i01.
I will fix it by using the new context.get-function to retrieve config-parameters.
