### ISSUE TITLE
/search: "sort": "default" fails

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#310]
If this isn't an error then spec.yaml should be updated

Error message:
{
  "statusCode": 500,
  "error": "TypeError: Cannot read property 'searchResult' of undefined"
}

Example request:
{ 
"q": "harry AND potter", 
"fields": ["identifier", "title", "collection", "subjectDBCF", "hasAdaptation"],  
"sort": "default",
"pretty": true
}

**Comment by rasmuserik** [comment]
Reproduced locally, I will look into this.
