### ISSUE TITLE
/search: if moreinfo request fails then the search fails too

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#311]
If a cover image is requested (alongside other fields) but the moreinfo-service fails (in this case it seems to be an authentication error), an error is returned. Is this expected behaviour?

Response:
{
  "statusCode": 500,
  "error": "Error: SOAP-ENV:Server: Error in request validation.\n Error: Element '{http://oss.dbc.dk/ns/moreinfo}identifier': This element is not expected. Expected is ( {http://oss.dbc.dk/ns/moreinfo}authentication ). on line 1"
}

Request:
{ 
"q": "harry AND potter", 
"fields": ["identifier", "title", "collection", "subjectDBCF", "hasAdaptation", "coverUrlFull"],  
"sort": "rank_title",
"pretty": true
}

**Comment by rasmuserik** [comment]
Tror at det er noget med driftssetup'et, så jeg assigner @adamtulinius 
Når jeg kører forespørgslen lokalt får jeg:
```json
{
  "statusCode": 200,
  "data": [
    {
      "title": [
        "Lego creator - Harry Potter"
      ],
      "collection": [
        "775100-katalog:24039978"
      ],
      "subjectDBCF": [
        "legoklodser"
      ]
    },
    {
      "title": [
        "Harry Potter-fænomenet"
      ],
      "collection": [
        "870971-faktalink:34568634"
      ],
      "subjectDBCF": [
        "Harry Potter-bøger",
        "Joanne K. Rowling",
        "børnelitteratur",
        "engelsk film",
        "engelsk litteratur",
        "film",
        "litteratur"
      ]
    },
    {
      "title": [
        "Harry potter and the half-blood prince"
      ],
      "collection": [
        "150061-ebog:ODN0000791016",
        "150061-netlydbog:ODN0000791532"
      ]
    },
...
```

**Comment by adamtulinius** [comment]
@ave-dbc Please retry the request

This bug was caused by a temporary change to the new moreinfo-service, which should be API-compatible, but apparently wasn't.

**Comment by ave-dbc** [comment]
Retried (on prod and stg) and it works now.

However, if the error (search fails because of moreinfo) was unintentional, I guess we should retry the request while the moreinfo-request fails?

**Comment by damkjaer** [comment]
I believe we decided that this was the correct behaviour - although the error-message could be better.
The decision was based on: If a backend service fails we do not know how to (generally) structure the result. And given the amount of time we had left it at that.

Please - someone - correct me if i'm wrong.

**Comment by damkjaer** [comment]
I have been convinced that it would be appropriate to return a list of empty results - one for each pid - from moreinfo in case a connection problem or similar occurs. The reason behind this is, if moreinfo is offline for some reason or another, then we can still return work-data. It is a problem, though, that we cannot communicate to the client that a moreinfo-error has occurred.
