### ISSUE TITLE
A few errors seen while there were production problems: neoWorkTransformer.js, facet, user.js

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#324]
It might be a good idea to check the code for correct errorhandling...

{"@timestamp":"2016-05-17T09:34:57.895Z","@version":1,"app":"serviceprovider","version":"0.0.1","level":"ERROR","host":"cbo","pid":7558,"msg":"TypeError: Cannot read property 'length' of undefined","stacktrace":"TypeError: Cannot read property 'length' of undefined\n    at workResponse (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/neoWorkTransformer.js:132:36)\n    at /home/cbo/serviceprovider/cboesgaard-branch/src/provider/neoWorkTransformer.js:185:12\n    at run (/home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/es6.promise.js:104:47)\n    at /home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/es6.promise.js:115:28\n    at flush (/home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/$.microtask.js:19:5)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"}

{"@timestamp":"2016-05-17T09:34:58.197Z","@version":1,"app":"serviceprovider","version":"0.0.1","level":"ERROR","host":"cbo","pid":7553,"msg":"response from facet-request","error":{},"errorString":"TypeError: Cannot read property 'facetResult' of undefined"}

{"@timestamp":"2016-05-17T09:35:01.721Z","@version":1,"app":"serviceprovider","version":"0.0.1","level":"ERROR","host":"cbo","pid":7553,"msg":"TypeError: Not a buffer","stacktrace":"TypeError: Not a buffer\n    at TypeError (native)\n    at pbkdf2 (crypto.js:562:20)\n    at exports.pbkdf2 (crypto.js:548:10)\n    at /home/cbo/serviceprovider/cboesgaard-branch/src/provider/user.js:49:5\n    at new Promise (/home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/es6.promise.js:197:7)\n    at Object.exports.default [as user] (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/user.js:48:19)\n    at Context._call (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/caller.js:106:42)\n    at Context.transformer (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/caller.js:188:17)\n    at Context.call (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/caller.js:179:19)\n    at Object.execute (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/Provider.js:58:44)"}

{"@timestamp":"2016-05-17T09:35:01.807Z","@version":1,"app":"serviceprovider","version":"0.0.1","level":"ERROR","host":"cbo","pid":7553,"msg":"TypeError: Cannot read property 'data' of undefined","stacktrace":"TypeError: Cannot read property 'data' of undefined\n    at workResponse (/home/cbo/serviceprovider/cboesgaard-branch/src/provider/neoWorkTransformer.js:108:31)\n    at /home/cbo/serviceprovider/cboesgaard-branch/src/provider/neoWorkTransformer.js:185:12\n    at run (/home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/es6.promise.js:104:47)\n    at /home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/es6.promise.js:115:28\n    at flush (/home/cbo/serviceprovider/cboesgaard-branch/node_modules/core-js/modules/$.microtask.js:19:5)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"}

**Comment by rasmuserik** [comment]
... and:

{"@timestamp":"2016-05-17T11:18:34.979Z","@version":1,"app":"serviceprovider","version":"0.0.1","level":"ERROR","host":"panther","pid":19338,"msg":"Ty
peError: Cannot read property 'collection' of undefined","stacktrace":"TypeError: Cannot read property 'collection' of undefined\n    at workResponse (/home/rasmuserik/serviceprovider/src/provider/neoWorkTransformer.js:139:40
)\n    at /home/rasmuserik/serviceprovider/src/provider/neoWorkTransformer.js:185:12\n    at run (/home/rasmuserik/serviceprovider/node_modules/core-js/modules/es6.promise.js:104:47)\n    at /home/rasmuserik/serviceprovider/n
ode_modules/core-js/modules/es6.promise.js:115:28\n    at flush (/home/rasmuserik/serviceprovider/node_modules/core-js/modules/$.microtask.js:19:5)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at pr
ocess._tickDomainCallback (internal/process/next_tick.js:122:9)"}

I will take a quick look at these in a moment.

**Comment by rasmuserik** [comment]
1. [ ] neoWorkTransformer.js:132
2. [ ] check for body.error && body.error.$ in facets.js
3. [x] user.js:49
4. [ ] neoWorkTransformer.js:108
5. [ ] neoWorkTransformer.js:139

**Comment by damkjaer** [comment]
It seems like work works :)
