### ISSUE TITLE
/suggest - limit fails with application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#325]
curl -sSL -H "Authorization: Bearer qwerty" -X GET --data-urlencode "q=harr" --data-urlencode "type=title" --data-urlencode "limit=6" "http://platform-i01.dbc.dk:8080/v0/suggest/"

Jonas gjorde opmærksom på denne i sidste uge på slack, for at den ikke bliver glemt opretter jeg den nu her.

**Comment by rasmuserik** [comment]
Hvis jeg kører:
```bash
curl "http://platform-i01.dbc.dk:8080/v0/suggest?access_token=qwerty&q=harr&type=title&limit=6&pretty=true"
```
Kommer følgende:
```json
{
  "statusCode": 200,
  "data": [
    {
      "str": "Harry Potter og Fønixordenen",
      "id": "870970-basis:24880605",
      "creator": "Joanne K. Rowling",
      "type": "book"
    },
    {
      "str": "Harry Potter and the deathly hallows - part 1",
      "id": "870970-basis:28529724",
      "type": "movie"
    },
    {
      "str": "Harry Potter - quidditch verdensmesterskaberne",
      "id": "870970-basis:25034937",
      "type": "other"
    },
    {
      "str": "Harry - med far i køkkenet",
      "id": "870970-basis:27002951",
      "creator": "Rikke Lauridsen",
      "type": "book"
    },
    {
      "str": "Harry alias Kammertjeneren",
      "id": "870970-basis:29534810",
      "creator": "Duncan Hamilton",
      "type": "book"
    },
    {
      "str": "Harriet the spy - blog wars",
      "id": "870970-basis:29170258",
      "type": "movie"
    }
  ]
}
```
hvilket umiddelbart er hvad jeg ville forvente.

**Comment by KiraH** [comment]
Det er helt korrekt, hvis du skriver sådan virker det. Som Jonas skriver på slack så er det kun 'content-type': 'application/x-www-form-urlencoded’, der ikke virker.

**Comment by rasmuserik** [comment]
Ok, fejlen skyldes: `--data-urlencode` parameteren til `curl`, post'er data og url-encoder det ikke i get-requesten.

**Comment by rasmuserik** [comment]
Jeg kan ikke lige få øje på Jonas( @hyatt03 )  besked i slack, - hvilken kanal er det i?

Umiddelbart understøtter vi kun JSON i POST-requests, hvilket er dokumenteret her: 

https://github.com/DBCDK/serviceprovider/blob/master/doc/api-design.md#transports

Er der et use-case hvor vi har brug for andet?

**Comment by damkjaer** [comment]
Kun application/json er understøttet POST.
