### ISSUE TITLE
context.json validation

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#329]
It would be nice to have a "central" place to validate "the context" has the necessary information, but also nice to be able to the declarative info into the different places it is used.

Goal: have the SP fail on startup if the context is not usable -- this might not be trivial...

Maybe we should brainstorm a bit about this?

**Comment by rasmuserik** [comment]
yes, it makes good sense to have a central place to validate the context.

We cannot validate it on startup, as it depends on the access_token (and the context of some access tokens might be valid, while others might fail), but we could validate it as the request comes in.

**Comment by adamtulinius** [comment]
So i think there are really two different issues here.

**1) part of a context-section is missing (like the url to opensearch in the "opensearch"-section)**
In this case the transformer should probably just return an error to the serviceprovider framework. As an alternative, each transformer could maybe register af list of required attributes, but this probably ends up rather complicated like the swagger-stuff.

2) **an entire section (e.g. "opensearch") of the context is missing**
I think a 401 or 403 should be returned in this case when hitting the relevant transformer, but I'm not sure where this should be handled.

(We've touched this issue briefly in the past, but the crux of the matter is that it should be possible to limit access to certain endpoints, even when an user is logged in.)

**Comment by rasmuserik** [comment]
A simple approach could be to validate that the context has all the fields that are present in the sample-context.

**Comment by rasmuserik** [comment]
I have added a simple implementation in #332. I do not know if this is sufficient?

I think it should be a 5xx error and not a 4xx error, as an error in the context is a server error and not a client error imho.

**Comment by adamtulinius** [comment]
> I think it should be a 5xx error and not a 4xx error, as an error in the context is a server error and not a client error imho.

An entire section missing is the same as the user not having permission to that endpoint, and thus 4xx is the way to go.

**Comment by adamtulinius** [comment]
If we want this bug closed, we should at least create a new bug that tracks denying an user access to a specific endpoint.

**Comment by rasmuserik** [comment]
Validation is temporarily disabled:
https://github.com/DBCDK/serviceprovider/blob/master/src/app.js#L219

**Comment by kkdbc** [comment]
@hyatt03 er den stadig aktuel?

**Comment by hyatt03** [comment]
@kkdbc Dette er meget relevant, da vi i højere grad laver specialiserede opsætninger i smaug. Vi overskriver punkter i konfigurationen med nye ting (f.eks. communityId), da dette er gjort i hånden er der risiko for fejl.
