### ISSUE TITLE
Is it possible to put the request+endpoint in the autogenerated tests?

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#354]
This would make the tests usable as examples and also make it rather easy to recreate the tests.

It could be in json or whatever format was easy to put in.

E.g. something like:

{
"endpoint": "recommend",
"request": {"recommender":"popular", "limit":3, "timings":true, "createTest":true}
}

**Comment by rasmuserik** [comment]
I just add a comment in the beginning of the file, with the endpointname and parameters (prefixing with `// Request:` to make it easily greppable)
