### ISSUE TITLE
Autogenerated unittests behaves a little strange when they fail...

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#358]
If I break a test, say:
src/provider/__tests__/rank-happy.js

By adding something to result in src/provider/rank.js
E.g. result.push("abemad");

And run the test, I expect it to fail, but not with a timeout:

  1 failing

  1) Automated test of the rank endpoint expected response. ID:3sx9lp, for {"pids":["870970-[...]

     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by rasmuserik** [comment]
Might be due to not catching errors from promise in autotests. 
Pull request added that solves that.

**Comment by cboesgaard** [comment]
I have just re-tested, and it is the same.

You can easily get the error by inserting a line in say rank.js:

diff --git a/src/transformers/rank.js b/src/transformers/rank.js
index f0dd8e4..d2f1cf2 100644
--- a/src/transformers/rank.js
+++ b/src/transformers/rank.js
@@ -43,6 +43,7 @@ export default (request, context) => { // eslint-disable-line no-unused-vars
           result.push(r);
         }
       }
+      result.push(2);
       return {statusCode: 200, data: result};
     });
   } catch (err){

**Comment by cboesgaard** [comment]
Ahhh, I think the problem is something else... There is a timout from mocha and travis is slooooow...
http://mochajs.org/#timeouts

**Comment by cboesgaard** [comment]
This might be a rather serious problem, as I have unittests failing on travis but not locally :-(

**Comment by cboesgaard** [comment]
I hacked it by adding this.timeout(0) -- but then some of the other tests seemed to disappear...
Now trying with timeout(5000). 
Both cases work fine locally but not on travis.

**Comment by cboesgaard** [comment]
This gives me:
1) Automated test of the recommend endpoint expected response. ID:0puhjc, for {"like":["870970-basis:45488713","870970-basis:28643713","870970-basis:29494940","870970-basis:29386404","870970-basis:28429576"],"recommender":"default","limit":10}:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

Trying 10000 :)

**Comment by cboesgaard** [comment]
3) Automated test of the recommend endpoint expected response. ID:9jjw37, for {"recommender":"popular","limit":3}:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by cboesgaard** [comment]
I cannot run the tests with success on travis, so they have been disabled for now...

**Comment by cboesgaard** [comment]
It looks like newly generated tests works.
