### ISSUE TITLE
unittest for transformers must be moved.

### ISSUE THREAD

**Issue by damkjaer** [DBCDK/serviceprovider#361]
The generated unittest (createTest: true) should be moved from src/provider/__test__ to src/transformers/__test__

No problem in moving the files, but the script that generates the files assumes the test_files are located a place where they can access '../Provider.js'. This is not true when moved to src/transformers/__test__ and the script must be updated to reflect this.

**Comment by cboesgaard** [comment]
And also to place the files different in the future.

**Comment by cboesgaard** [comment]
This will be solved when new tests are generated.
