### ISSUE TITLE
Request behaves strangely

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#379]
From Jonas:

curl -H "Authorization: Bearer qwerty" -H "host: platform-i01.dbc.dk:8080" -H "content-type: application/x-www-form-urlencoded" -H "content-length: 112" --data-binary "pids%5B0%5D=775100-katalog%3A42946400&fields%5B0%5D=coverUrlFull&fields%5B1%5D=collection&fields%5B2%5D=workType" http://platform-i01.dbc.dk:8080/v0/work/

gives empty answer:
{"statusCode":200,"data":[{}]}

**Comment by rasmuserik** [comment]
Umiddelbart tror jeg at det er et konfigurationsspørgsmål, om at materialet ikke er i den samling i slår op i, i opensearch, i.e. både:

```
curl http://platform-i01.dbc.dk:8080/v0/work'?access_token=qwerty&pids=\["775100-katalog:42946400"\]'
curl http://platform-i01.dbc.dk:8080/v0/search'?access_token=qwerty&q="rec.id=42946400"'  
```
giver ingen resultater, hvorimod samme forespørglser finder det pågældende materiale med localhost i stedet for platform-i01.dbc.dk. Forskellen på de to burde blot være contexten fra smaug.

Reassigner denne tilbage til @hyatt03 som kan afgøre om den kan lukkes, eller om den skal gives videre til nogen der skal opdatere contexten for platform-i01.dbc.dk

**Comment by hyatt03** [comment]
Det ser ud til at i har ret, vi søger i en pallebrønd efter noget der ikke er i en pallebrønd. Jeg lukker den :)
