### ISSUE TITLE
OAuth etc. from openserviceprovider

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#4]
Merge the code from https://github.com/DBCDK/openserviceprovider into this repository where applicable.

**Comment by adamtulinius** [comment]
FYI: We've been talking about moving the auth/token management to another project, instead of merging it into this project.

**Comment by rasmuserik** [comment]
Yep, I somewhat assumed that we would expand on / clean up / do that in openserviceprovider, where Mattias has already started on it.

**Comment by adamtulinius** [comment]
See https://github.com/DBCDK/smaug
