### ISSUE TITLE
Use of context from transformers

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#407]
We talked about this yesterday. I have a few points.

(1) Maybe we should wrap the usage in a function to have level of indirection (logging, validation, easy way to control/check usage)? I.e. instead of context.data.rank.url we would have something like: context.get("rank.url")/get(context, "rank.url")

(2) rank uses:
context.data.rank.url

(3) recommend uses:
context.data.app.collectionidentifiers
context.data.recommend.urls

**Comment by FlashGordon** [comment]
If we go ahead with a function approach, maybe it should be possible to fetch whole chunks of data, like context.get('userstatus')? in a lot of user/order/renew multiple fields are fetches (about 10-15). so a call for each value will result in a bit of clutter.

**Comment by cboesgaard** [comment]
I guess this is kind of fixed now with get and a new context layout
