### ISSUE TITLE
Authentication seems to break CORS

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#410]
When making a CORS http-post request, 
the browser first sends an http-options request,
which fails with 403, apparently due to our
authorization-middleware.

**Comment by rasmuserik** [comment]
Only affects json/post requests, which have low priority, as websockets makes more sense on the browser platform. Only affected platforms would be webapps targeting `<= IE9, OperaMini`, which do not support websockets. Conclusion from meeting: postpone issue to 1.1. Will make pull request that updates documentation.

**Comment by kkdbc** [comment]
forældet
