### ISSUE TITLE
Use new context (context.get('...')) in the transformers

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#422]
... instead of context.data.•••

Updated the following files:

- [ ] availability.js
- [ ] cancelOrder.js
- [x] ddbcms.js
- [x] facets.js
- [ ] getOrderPolicy.js
- [x] libraries.js
- [x] moreinfo.js
- [ ] openHoldingStatus.js
- [x] opensearchGetObject.js
- [x] opensearchSearch.js
- [ ] order.js
- [ ] placeOrder.js
- [x] rank.js
- [x] recommend.js
- [x] renew.js
- [x] search.js
- [ ] suggest.js
- [ ] testTransformer.js
- [ ] user.js
- [ ] work.js

**Comment by cboesgaard** [comment]
This should not be done before integration + prod is ready. ATU will give green light.

BTW.:#423 fixes a bug in context.get().

**Comment by cboesgaard** [comment]
This is the story grep tells:

cancelOrder.js:  let userstatus = context.data.userstatus;
ddbcms.js:  let config = context.data.ddbcms;
facets.js:  let agency = context.data.opensearch.agency;
facets.js:  let profile = context.data.opensearch.profile;
moreinfo-2.1.js:        authenticationUser: context.data.moreinfo.user,
moreinfo-2.1.js:        authenticationGroup: context.data.moreinfo.group,
moreinfo-2.1.js:        authenticationPassword: context.data.moreinfo.password
moreinfo.js:    authenticationUser: context.data.moreinfo.user,
moreinfo.js:    authenticationGroup: context.data.moreinfo.group,
moreinfo.js:    authenticationPassword: context.data.moreinfo.password,
opensearchGetObject.js:  if (!context.data.opensearch) {
opensearchGetObject.js:  let osContext = context.data.opensearch;
opensearchSearch.js:  let agency = context.data.opensearch.agency;
opensearchSearch.js:  let profile = context.data.opensearch.profile;
suggest.js:  let localParams = {query: params.q, lt: context.data.librarysuggest.librarytype};
suggest.js:                     filter: context.data.app.collectionidentifiers};
user.js:    if (context.data.ddbcms) {
user.js:      data.ddbcmsapi = context.data.ddbcms.url;
work.js:    let moreinfoUrl = context.data.services.moreinfo;

**Comment by cboesgaard** [comment]
Context format has been updated, see slack for details.

**Comment by cboesgaard** [comment]
Unchecked recommend and rank.

**Comment by cboesgaard** [comment]
It might be a good idea to solve these in their own issues, and refer to these here...

**Comment by damkjaer** [comment]
search, work and moreinfo* fixed.

**Comment by cboesgaard** [comment]
Verified done (by grep etc.)
