### ISSUE TITLE
/order: library interpreted as agency

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#440]
The value of library in an order overrules the agency set in the configuration. For instance on http://platform-i01:8080/v0/ with token "ave" agency is set to 830380, but with the request below the order is actually ordered through the agency 830690 (these are two different agencies, not just branches of the same agency).

This is not obvious from the spec, and it also differs from what @rasmuserik and ANM expected when we discussed this earlier today.

I assume that the value of "library" is used as pickUpAgencyId in the openorder-request that the sp creates, as pickUpAgencyId determines the agency or branch through which the material will be ordered.

Request:
{ 
"pids": ["830380-katalog:51567242"], 
"library": "830690",
"pretty":true,
}

**Comment by rasmuserik** [comment]
I will update the spec, to explicit say that the library should be a branch of the currently logged in agency.

**Comment by rasmuserik** [comment]
@FlashGordon could you check that branch/agency is used in the right way?

**Comment by FlashGordon** [comment]
After discussion with AVE and Rasmuserik. This issue is resolved

**Comment by DDBdrift** [comment]
Order still includes library, but not branch (alias pickUpAgencyId):
```
"orders": [
            {
                "orderId": "normal:10243496",
                "status": "Active",
                "library": "DK-726500",
                "holdQueuePosition": "1",
                "creator": "Deadmau5",
                "title": "4x4=12 (Joel Zimmerman)",
                "orderDate": "2017-03-28T00:00:00+02:00"
            },
```

**Comment by hrmoller** [comment]
pickUpAgency is mapped to library. See https://github.com/DBCDK/serviceprovider/blob/master/src/transformers/user.js#L57
