### ISSUE TITLE
/events, /news error

### ISSUE THREAD

**Issue by ave-dbc** [DBCDK/serviceprovider#441]
/events and /news returns {"statusCode":500,"error":"Error: connect ECONNREFUSED 52.29.166.250:80"}. I know this is probably a known issue. Might just be a configuration thing.

Tested on http://platform-i01:8080/v0/ and http://platformbe-p01.dbc.dk:8080/v0/ with various tokens.

**Comment by cboesgaard** [comment]
Yes, this is a firewall issue. CSV is expected to fix this.
