### ISSUE TITLE
The automated unittest should output the testfile name

### ISSUE THREAD

**Issue by FlashGordon** [DBCDK/serviceprovider#458]
The automated unittest should output the testfile name, instead of just the endpoint name

**Comment by rasmuserik** [comment]
Where should the testfile name be output'ed?

**Comment by FlashGordon** [comment]
When the test is run, I can see the describe string is output
Example: 'Automated test of the order endpoint',
It would be nice to know which test is failing when there are multiple tests of the same endpoint
