### ISSUE TITLE
/renew endpoint issues

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#466]
``` javascript
dbcOpenPlatform.renew({loanId:'NCIPMDAxOXw5OTAwfHw5OTAwLnx8'});
```

yields

``` javascript
 {statusCode: 500, error: "TypeError: Cannot read property '0' of undefined"}
```

(for anonymous user, who have the above loan listed in /user)

**Comment by rasmuserik** [comment]
When testing against real user on Københavns Biblioteker, `/renew` works fine (with valid loans, and also has decent error message when loan cannot be renewed).

This bug is kept open, as some error-condition apparently is not handled, but if the API is used correct, it appears not to appear. - moved to backlog.

**Comment by kkdbc** [comment]
forældet
