### ISSUE TITLE
stop depending on vibjerg/jsonpath-object-transform

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#48]
Either vendor the dependency, move it to DBCDK, or replace it with something else.

**Comment by damkjaer** [comment]
This only happens in:
transformers/moreinfo/CoverImage.transform.js

I have rewritten the transformer to the Neo-style, and it does not depend on the above dependency.
When we remove old transformers this dependency is going the way of the do-do.

**Comment by damkjaer** [comment]
To be removed when old transformers are deleted!
