### ISSUE TITLE
/order endpoint issues

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#481]
I am testing order, with real library/user, (with local context for ordering from Københavns Biblioteker (710100) and proper cpr/pin), and the request is:

``` url
http://localhost:8080/v0/order?access_token=qwerty&pids=["775100-katalog:05193370"]&library="710110"&name=RasmusErik%20Voel%20Jensen&email=openplatform-dbc-dk@solsort.com
```

then the result status is

``` json
{"statusCode":200,"data":{"status":"ok"}}
```

but the order has still not shown up in userstatus (neither on serviceprovider, nor bibliotek.kk.dk) after an hour.

Has anybody else got orders through on actual users (not just the test user)?

**Comment by rasmuserik** [comment]
maybe check that parameters derived from user_id/pin is passed on when needed. I.e. birthday, cardno, ...

**Comment by rasmuserik** [comment]
Also see #477

**Comment by FlashGordon** [comment]
In the sample context we use the openorder test url. We should make sure it's the real url that is being used in production

**Comment by rasmuserik** [comment]
`delete: true` on existing orders works fine (on københavns biblioteker), so it is only creating new orders that fails.

**Comment by rasmuserik** [comment]
The way I call order is:
```js
dbcOpenPlatform.order({pids: ["870970-basis:29040427"], library:"710100"}).then(o => console.log(o));
```

**Comment by cboesgaard** [comment]
What Rasmus says is that  an "OK" is returned, but the order is not actually to be found later.

We need to find out what actually happens, if the WS responds with ok, things should be ok from the SP perspective, and the bug should be sent to WS owners.

**Comment by rasmuserik** [comment]
Det virker :) delvist :(

Sendte nogle bestillinger for lidt siden,
og der var én der gik igennem..

**Comment by kkdbc** [comment]
afventer aktuelle problemer
