### ISSUE TITLE
cleanup files/directories in repository

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#485]
While working on the documentation, I realise a lot of things that we could cleanup. Instead of creating individual bugs #484, #336 , I try to collect it in this one:
- [x] either delete `dockerfile`, `docker-compose.yml`, and `.dockerignore`, or make make them not reference Palles Gavebod
- [x] do we use forever? otherwise delete `.foreverignore`
- [ ] ~move the different tests `apitest/`, `ave-test/`, `performancetest/`, `add_imports_to_tests.py`, `mocktest.sh`, `siegetestendpoints.txt` into one directory, say `tests/`, to not clog root directory.~ Moved to #729
- [x] `src/` - does it make sense to have subdirectories with only a single or two files?, - otherwise move them one directory up.
- [x] remove siege from `package.json` (or if we intend to use it, add `siegedemoendpoints.txt`)
- [x] remove references to `log.log` in `package.json`, as afaik we changed logging to stdout? (or not, - only app.js seems to use some of dbc-node-logger. - is this intentional?)
- [x] `.travis.yml` probably does not need `SMAUG=invalid` environment
- [x] upgrade dependencies, removed unused (`cache-manager`, `dbc-node-basesoap-client`, `helmet-csp`, `node-rest-client`, `to-iso-string` (or wasn't this missing dependency for other dependency), `sanitize-html`, `sinon`, `xml2js`, `xmldom`, `xpath`, `xss-filters`  not used?)
- [x] Loggers - should utils.log replace all of `dbc-node-logger` or is it intentional that we keep it in app.js. - this is probably #71 / #510
- [x] I do not think coverage is working at the moment? Either make it work or remove it.
- [x] remove `testlib/`?
- [x] go through [code-climate](https://codeclimate.com/github/DBCDK/serviceprovider/code), and look at the issues not related to autogenerated tests. Also make autogenerated tests be ignored.

**Comment by hrmoller** [comment]
@adamtulinius har du styr på hvorvidt der bruges forever og/eller docker?

**Comment by adamtulinius** [comment]
@hrmoller: I bruger vist forever i.f.m. deployment, men det burde flåes ud til fordel for systemd uanset hvad. Docker bruges ikke pt., men det burde vi nok kigge på, især i.f.m. med at køre SP og Smaug på Mesos.

**Comment by hrmoller** [comment]
@adamtulinius OK jeg sletter dockerfilerne

**Comment by hrmoller** [comment]
We do use forever for running in local dev mode and in dev CI env

**Comment by hrmoller** [comment]
Dockerfiles removed

**Comment by hrmoller** [comment]
Siege removed

**Comment by hrmoller** [comment]
`SMAUG=invalid` removed from `.travis.yml`

**Comment by hrmoller** [comment]
Dependencies upgraded/removed

**Comment by hrmoller** [comment]
dbc-node-logger removed

**Comment by hrmoller** [comment]
@hyatt03 fixed covereage

**Comment by hrmoller** [comment]
`testlib/` removed

**Comment by hrmoller** [comment]
no serious current code-climate issues. SonarQube has been established as part of our CI setup to continuously monitor changes in complexity, code smells, etc.

[SonarQube](http://www.sonarqube.org/)
