### ISSUE TITLE
Update ddbcms to use new context + get

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#494]
Also see #422.

This is just a few lines of fixes:
https://gist.github.com/cboesgaard/9437edc3de76f32a4f1920934b04200e

But I could not rerun the the tests due to:
"message\":\"Failed validating request. Check your credentials (agency & key).\"

I am using the same agency as the existing test and the credentials in the context:
775100 and d8...

How do I get a valid credential?

**Comment by rasmuserik** [comment]
775100 and d8... should be valid, - I got it from the old mobilsøg config.
They appear to work, - I have sent you an url on slack.

**Comment by rasmuserik** [comment]
The gist you made works, - I just copied it into `transformers/ddbcms.js` here, and it works fine when I test it with a context with user.agency=775100. The difficulties is to test it, as the order-test-user has agency 100451, and the test-ddbcms-agency is 775100, and thus they cannot be tested with the same context :(
