### ISSUE TITLE
Update facets and search to use new context

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#495]
Also see #422.

**Comment by cboesgaard** [comment]
facets.js

I was not able to re-record these tests:

facets_zero_limit.js
facets_negative_limit.js

facets {"q":"harry AND potter","fields":["creator"],"limit":-1,"createTest":"facets_negative_limit"}
facets {"q":"harry AND potter","fields":["creator"],"limit":0,"createTest":"facets_zero_limit"}

**Comment by damkjaer** [comment]
Search fixed.

**Comment by cboesgaard** [comment]
Considered done
