### ISSUE TITLE
Test localhost/platformbe-p01 [not really an issue, more like some information]

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#527]
I did a quick test of all the endpoints. Three responses might need som explanation:

(1) events results in empty list
curl -sSL -w "\nCURL HTTPCODE=%{http_code} SECS=%{time_total}\n" -H "Authorization: Bearer XXX" -H "Content-Type: application/json" -X GET -d '{"fields": ["title", "changed", "nid", "field_ding_event_title_image"], "timings":true}' "http://localhost:8080/v1/events"
{"statusCode":200,"data":[],"timings":{"total":272,"external":271}}
CURL HTTPCODE=200 SECS=0,307

(2) news results in empty list
curl -sSL -w "\nCURL HTTPCODE=%{http_code} SECS=%{time_total}\n" -H "Authorization: Bearer XXX" -H "Content-Type: application/json" -X GET -d '{"fields": ["title", "changed", "nid", "field_ding_news_list_image"], "timings":true}' "http://localhost:8080/v1/news"
{"statusCode":200,"data":[],"timings":{"total":112,"external":111}}
CURL HTTPCODE=200 SECS=0,153

The explanation for (1) and (2) is that the agency does not match the library with a working service. And it seems that the default url is for the testsystem (the only known system).

(3) renew returns:
{"statusCode":500,"error":"TypeError: Cannot read property '0' of undefined"}
This is not a problem for logged in users. Also see #466.

**Comment by kkdbc** [comment]
ingen relevans
