### ISSUE TITLE
Orders that cannot be deleted.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#531]
Order can lead to a state, where the order cannot be deleted, - the following order, which was made with the serviceprovider:

```
author: "Franklin, Benjamin"
holdQueuePosition: "1"
library: "DK-710100"
orderDate: "2016-05-31T00:00:00+02:00"
orderId: "Hold:-1857356"
status: "Requested via ill"
title: "The autobiography of Benjamin Franklin"
```

cannot be deleted (via DDBCMS bibliotek.kk.dk).

Hopefully this is an exceptional case (most of the orders I made with the ServiceProvider worked fine, and was deleteable).

**Comment by kkdbc** [comment]
skyldes at den oprindelige bestilling har affødt en ill-bestillin, denne kan kun slettes manuelt. wontfix
