### ISSUE TITLE
errorhandling for failing web services (moreinfo)

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#537]
Today we had a problem with the moreinfo webservice (it was broken). But when it failed, the response from the SP was just:

{"statusCode":500,"error":"TypeError: Cannot read property '0' of undefined"}

This illustrated some things that could be improved:
- endpoints should log errors from webservices as errors to ease debugging.
- in some cases it might be a good idea to return the error back
- search should handle the error from work (other endpoints should also be checked for this kind of handling)

**Comment by kkdbc** [comment]
fixed for længe siden.
