### ISSUE TITLE
Create API-spec

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#54]
After writing the API-spec, a list of tasks should be created describing each API method.

**Comment by rasmuserik** [comment]
- The API-spec, is done in `spec.yaml`. 
    - can be viewed as swagger-documentation on localhost:8080 during `npm run dev`
    - the `spec.yml` file includes extra examples, that are not shown by swagger.
- I have added issues for each endpoint, where we can discuss implementation specific details that does not belong in the spec. Also added notes to some of these.
