### ISSUE TITLE
Forsidebillede udleveres ikke for værk, der har forside på andet pid end det primære

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/serviceprovider#542]
"Harry Potter og hemmelighedernes kammer" med primær pid 870970-basis:22677780 har ikke nogen forside. Men andre pid'er i værket har forsider. Der skal derfor returneres en forside URL for et af de andre pid'er. 
Primær pid: 870970-basis:22677780
Sekundær pid med forsidebillede: 870970-basis:29316945
Søgning på Biblo:
https://biblo.dk/find?q=%22Harry%20Potter%20og%20Hemmelighedernes%20Kammer%22&emneord=&materialer=book
Visning af værk på Biblo:
https://biblo.dk/materiale/870970-basis:22677780

**Comment by rasmuserik** [comment]
Lige en hurtig kommentar, - selvom jeg egentlig har givet den videre.

Min anbefaling er, at dette løses i de bagvedliggende services, og ikke i
ServiceProvideren. Det pæneste vil i mine øjne være:
at BriefDisplay i opensearch udvides med en hasCoverImage-property,
hvorefter klienten ved hvilken pid den skal spørge efter forsidebillede på.

Hvis I vælger at lægge dette logik i ServiceProvideren, kommer der nogle
ikke-trivielle overvejelser om hvordan værk-egenskaber på manifest-niveau
skal håndteres, således at det både er konsistent, og ikke går ud over
performance.
(ServiceProvideren arbejder konceptuelt med materialer på manifest-niveau,
hvor det konkrete manifest også har en collection-property med andre
manifester i værket. Søgning returnerer blot et manifest fra collection'en.
Hvis manglende forsidebillede skal medføre, at der skal findes et andet
forsidebillede, bør man nok tilføje en ny property collectionCoverImage,
eller lignende. Bemærk også at collection-property'en er ikke nødvendigvis
kendt, når der bliver forespurgt om forsider (ie. med work), - hvilket kan
gøre det langsomt at have med som default).

En enkel løsning på klientsiden, her og nu, er at sende en forespørgsel til
work-endepunktet med fields=coverUrlFull, med de pid'er der er i
collection'en på materialet, hvorved man får alle forsider i værket.

Jeg kan ikke huske om der er informationer om eksistens af forsider i
opensearch, eller om man skal spørge moreinfo. Under alle omstændigheder
ville det gøre opslaget enklere/hurtigere, hvis der var en information i
BriefDisplay/solr om hvorvidt det pågældende materiale har en forside.

**Comment by vibjerg** [comment]
Problemet kan ikke genskabes. Når man søger på harry potter og hemlighedernes kammer på biblo, får man samme forsidebilleder som på bibliotek.dk Hvis man søger på 870970-basis:22677780 får man ikke noget forsidebillede på hverken bibliotek.dk eller på biblo.dk
