### ISSUE TITLE
token storage

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#55]
I think we have to figure out how long a token should be stored (or, in other words, how often a user is expected to login on a device)

Currently tokens are stored in Redis, so we have to evaluate the persistence mechanism of Redis if the goal is longterm token storage (e.g. users might be logged in for weeks at the time, or indefinitely), and possible use something else if we don't like what we see.

**Comment by rasmuserik** [comment]
My immediate thought is that it would be nice to have it at least one month (same as the usual maximum lending time).

Indefinitely might even be better, as we then also do not have to think about renewal etc.

Redis has the option to be disk-backed, and if something happens such the tokens gets lost, it would only mean that the user had to log in again, - so in my opinion it would be fine for the first version of the AuthServer.

**Comment by adamtulinius** [comment]
Agreed.
However, we need to figure out where we're going to put the configuration data. I'm not sure Redis is the right tool for storing that long term; maybe a more traditional database will be better suited for that, and -- if that is the case -- it might be a bit silly to store configuration one place, and tokens another.
