### ISSUE TITLE
repository cleanup

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#56]
We should probably remove (or archive?) the original serviceprovider repositories at some point, to avoid confusion. Currently the following repositories have way too similar sounding names:
- serviceprovider
- openserviceprovider
- dbc-node-serviceprovider

**Comment by hrmoller** [comment]
You're right but i.e. in [Biblo](https://github.com/DBCDK/biblo/blob/master/package.json#L72) the old serviceprovider (dbc-node-serviceprovider) is still used as an component within the application. However, I guess openserviceproivder could be removed  right away.

**Comment by BettinaAndersen** [comment]
Relevans overskrevet
