### ISSUE TITLE
Logs from ServiceProvider should be accessible in ELK

### ISSUE THREAD

**Issue by hrmoller** [DBCDK/serviceprovider#566]
Maybe through Kafka?

**Comment by KiraH** [comment]
Da alle vores applikationer logger til syslog, er logfilerne søgbare gennem kibana. Men vi skal have ændret på opbygningen af logfilerne, hvis vi for alvor skal kunne få noget ud af dem. 

ERS må kunne svare på hvordan de skal være opbygget for at man automatisk kan få genereret labels for de forskellige dele af logfilen. Pt ligger den bare som en json klump.

**Comment by rasmuserik** [comment]
Note fra #808: [json filter plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html)

**Comment by rasmuserik** [comment]
Tak til ERS, der nu har konfigureret ELK'en så json-strukturene bliver udpakket :)
Dette løser så vidt jeg kan se issuet.

Note: ELK'en er ved at blive opgraderet, så det giver mening at vente med implementation af dashboard til efter dette.

**Comment by KiraH** [comment]
done
