### ISSUE TITLE
Link in description breaks paragraph width

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/serviceprovider#597]
https://openplatform.dbc.dk/v1/
Select ”Show” -> GET "Work"
The column ”Data Type” is hidden outside the window due to a long link in the description. The link text should be shortened in order to show the "Data Type" column.

**Comment by AndersFriisBrodsgaard** [comment]
Reference in DBC Nilex 44672

**Comment by fvsdbc** [comment]
Fixed med work-break i screen.css
