### ISSUE TITLE
Ordering material sets userName to 'name', userTelephone to 'phone' and userMail to 'email'

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/serviceprovider#598]
The parameters should be set to data from params 

https://github.com/DBCDK/serviceprovider/blob/master/src/transformers/placeOrder.js#L66

**Comment by fvsdbc** [comment]
![bob_name_email_phone](https://cloud.githubusercontent.com/assets/3070049/18630255/898cb210-7e6b-11e6-9de9-ff628a905121.png)

**Comment by kkdbc** [comment]
vi fixer mapningen
