### ISSUE TITLE
Serviceprovider fails if moreinfo is unavailable

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#600]
If you make a request with coverUrls and moreinfo is unavailable you get the following error:

 `body: '{"statusCode":500,"error":"CoverUrls could not be fetched. Server probably unavailable. Try request again without coverUrls."}'`

Instead a valid search result should be returned together with an error message for the failed underlying service.

**Comment by hyatt03** [comment]
Fixed in #601
