### ISSUE TITLE
testbruger virker ikke for ishøj

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#626]
Token udleveres korrekt, men testbrugeren virker ikke.

Fejlen er rapporteret ind i servicedesk og SVI har genskabt den.

følgende er indrapporteret med samme fejl:
Vesthimmerland og Tårnby.

Ishøj (718300)
Vesthimmerland (782000)
Tårnby (718500)

**Comment by kkdbc** [comment]
følgende er indrapporteret med samme fejl:
Vesthimmerland og Tårnby.

Ishøj (718300)
Vesthimmerland (782000)
Tårnby (718500)

**Comment by hyatt03** [comment]
Testbrugeren virker såfremt man benytter bibloteksnummer med foranstillet DK-
Eksempel:
`curl --user "CLIENT_ID":"CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d 'grant_type=password&username=LOANER_ID@DK-718300&password=LOANER_PIN'`

**Comment by DDBdrift** [comment]
FBS understøtter kun ISIL (DK-775100). DDElibra understøtter også suffix (775100) ved login.

Login i Aarhus (FBS) kan kun ske med `DK-775100`. I Roskilde (DDElibra) kan man logge på med både `DK-726500` og `726500`

Ved reference til Agency i fx /Libraries kan der kun søges UDEN suffix.

`curl -X GET --header 'Accept: application/json' 'https://openplatform.dbc.dk/v1/libraries?access_token=eaeb8efa455e149d3a29d2de85d6093ec3982fb1&agencyIds=%5B%22775100%22%5D'`
Svarer korrekt

`curl -X GET --header 'Accept: application/json' 'https://openplatform.dbc.dk/v1/libraries?access_token=eaeb8efa455e149d3a29d2de85d6093ec3982fb1&agencyIds=%5B%22DK-775100%22%5D'`
Returnerer status 200 og en tom liste

**Comment by DDBdrift** [comment]
Dokumentationen burde opdateres. Begrænsningen fremgår ikke af
https://openplatform.dbc.dk/v1/guide.html
