### ISSUE TITLE
When a sub service fails and returns 500, statusCode 200 is returned by serviceprovider

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#627]
How should the serviceprovider respond to a failing service.

As a minimum we need to make sure, that errors are logged in the service, but users of the serviceprovider should also receive some kind of error message.

**Comment by kkdbc** [comment]
der bør ses på logning

**Comment by vibjerg** [comment]
Jeg kan ikke genskabe de problemer der har været tidligere. Fejl bliver logget og der bliver sendt fejlbeskeder videre til brugere af serviceprovideren
