### ISSUE TITLE
author should be creator

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#633]
In the example response of [/user](https://openplatform.dbc.dk/v1/#!/Status/get_user) endpoint it says author under orders. It should be creator:

`  "orders": [
      {
        "orderId": "24181913",
        "title": "Morder-Anders og hans venner",
        "author": "Jonasson, Jonas",
        "status": "In process"
      }
    ],`

**Comment by kkdbc** [comment]
jeg mener det skal være omvendt. creator er et bredere begreb, ellers kan fx en dirigent få betegnelsen author.

**Comment by hrmoller** [comment]
Så altså "author should be creator"

**Comment by kkdbc** [comment]
Done. ikke lukket ved en fejl
