### ISSUE TITLE
"opac" profile in VIP required

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#651]
The provider uses the ”opac” as default profile in OpenSearch. If a profile with this title is NOT defined in VIP, the search result will be empty
VIP:	J. OpenSearch 3.x, 4.x

**Comment by vibjerg** [comment]
@DDBdrift Har i mulighed for at give nogle eksempler på biblioteker ikke har en opac søgeprofil, og der fejler. 

Er det en mulighed at få bibliotekerne til at oprette en søgeprofil, som hedder opac?

Det er pt. kun muligt at specificere ét profilnavn pr klient.

**Comment by DDBdrift** [comment]
@vibjerg Desværre ikke længere.
Roskilde havde omdøbt deres ”opac” profil til et andet navn. Derfor var der ingen forbindelse fra Den åbne platform.

Egentlig burde der være en default brøndprofil i VIP-basen. Men det er ikke angivet.
Såfremt der ikke er en ”opac” kunne man vel vælge den første brøndprofil i VIP?!

**Comment by vibjerg** [comment]
@DDBdrift Jeg undersøger om der en farbar løsning ifb. en integration med VIP-basen

**Comment by kkdbc** [comment]
der laves en optional søgeprofil angivelse.
