### ISSUE TITLE
Ved login skal Agency angives med ISIL nummer (DK-999) [KRITISK]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#659]
Begrænsning på Agency ved login fremgår ikke af dokumentationen i fx. 
https://openplatform.dbc.dk/v1/guide.html
Bør opdateres.
Se evt. #626

**Comment by DDBdrift** [comment]
OBS! Logger man en bruger på kræver FBS at der er et DK-præfiks. Man kan IKKE logge på som anonym biblioteksbruger med DK-præfiks.

**Comment by kkdbc** [comment]
SMAUG skal tilføje isil, hvis det kun er biblioteksnummer.

**Comment by vibjerg** [comment]
Løsningen fungerer ikke med default søgeprofil 190101
