### ISSUE TITLE
openplatform ser ud til at fejle ved søgning

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#681]
Jeg får forøjeblikket følgende fejl:

```
{"statusCode":500,"error":"TypeError: Cannot read property 'manifestation' of null"}
```
når jeg forsøger at lave søgninger via `/search` endpointet i den åbne platform, hvilket blokerer mit udviklingsflow :(

Det gælder både den app som jeg udvikler på, og også ældre app, der bruger den åbne platform og normalt virker.

Eksempelkode der fremprovokerer fejlen (via js-api'et):

``` javascript
dbcOpenPlatform.search({q:'hello'})
    .then(o=>console.log('ok', o))
    .catch(e => console.log('err', e));
```

skriver:

```
err Object {statusCode: 500, error: "TypeError: Cannot read property 'manifestation' of null"}
```

til konsollen. Der er logget korrekt ind, og anden funktionalitet virker uden fejl.

**Comment by hrmoller** [comment]
Tak for rapporteringen. Det er en underliggende service der fejler og der er folk på sagen.

**Comment by hrmoller** [comment]
Problemet bør være løst nu. Kan du evt. verificere @rasmuserik ?

**Comment by rasmuserik** [comment]
@hrmoller Bekræftet, - det virker her nu :)

**Comment by hrmoller** [comment]
i `transformers/opensearchSearch.js` ca. linje 65 bør der tjekkes for om `briefDisplay` er tilgængelig.
