### ISSUE TITLE
Versionering af API’et [KRITISK]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#683]
(Dette er et afklaringspunkt)
Versioneringen er en smule uklar. 
Hvilken sammenhæng er der mellem kode på Github og den kørende version?
Versionering skal tænke eksterne leverandører ind. Hverken API, argumenter eller format på data må ændre sig uden at der laves en ny version.

**Comment by kkdbc** [comment]
kun hvis forespørgsler og/eller svar ændres i serviceprovideren, opversioneres ÅP. Eksternt skifter vi fra 1 til 2 til 3 osv. (major) Den præcise version kan ses i footer.
pt. har vi nyeste + 1
NB. Der skal laves en aftale om varsel og hvor mange versioner der med rimelighed kan driftes bagud.
