### ISSUE TITLE
Statuskoder i HTTP-header [KRITISK]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#684]
Brug Http header til statuskoder i stedet for JSON body. Det gør tolkning lettere.

Eksempel:
https://openplatform.dbc.dk/v1/search?access_token=101f7f0e343295541ad58e827369caf18c6e60e5&q=nisse

Response Code: 200
Response Body: 
{
  "statusCode": 500,
  "error": "TypeError: Cannot read property 'manifestation' of null"
}
Det er betydeligt tungere, at skulle lave to tjek

**Comment by kkdbc** [comment]
skal understøtte både sockets og rest. Det medtages begge steder. Statuskode tilføjes til header.
