### ISSUE TITLE
Fejlkoder i søgning afspejler ikke søgeresultat [KRITISK]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#696]
Fejlkode i jason er 200 = OK uanset om søgning lykkes eller ej.
/libraries: Søgning på ikke eksisterende agency giver OK

**Comment by kkdbc** [comment]
ændring til 204 "no content"

**Comment by hyatt03** [comment]
Modsætning af #684

**Comment by hyatt03** [comment]
#684 kræver at statusCode bliver smidt i http header, denne issue giver anledning til en statusCode 204, hvilket i http headeren vil medføre at envelopen ikke bliver sendt til klienten. Altså er #696 og #684 inkompatible.

**Comment by hyatt03** [comment]
Bliver lukket grundet overstående.
