### ISSUE TITLE
Fuld brugerprofil i /Status/user [PROBLEM]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#697]
Pt returneres kun intern brugerID, samt lånerstatus. Der mangler navn, email, sms.

**Comment by kkdbc** [comment]
hvis email og sms findes (optional) skal SP udlevere data

**Comment by vibjerg** [comment]
Vi har ingen informationer om brugeren, og kan derfor ikke returnere nogen data.

**Comment by DDBdrift** [comment]
Øh, provideren henter lånerstatus fra lokalsystemet: User status, including arrived loans, orders, unique id, etc.
Hvorfor ikke hente navn, adresse, e-mail ? Det virker ulogisk, at man har CPR, men ikke navn til klienten.

**Comment by vibjerg** [comment]
Provideren, benytter servicen openuserstatus til at vise status, og den service udleverer ikke informationer om brugeren, udover bruger id.

**Comment by DDBdrift** [comment]
Er det så den service, der skal udvides? Data burde kunne hentes fra lokalsystemet

**Comment by vibjerg** [comment]
Ja, det skal det, så vidt jeg kan se, være. Jeg taler lige med @kkdbc om det.

**Comment by fvsdbc** [comment]
OpenuserStatus bruger ncip protokollens LookupUser til at hente data fra lokalsystemerne (http://www.ncip.info/the-standard.html). Historisk har lokalsystemerne ikke udfyldt felter med brugernavn osv (email findes vist ikke som mulighed i ncip LookupUserResponse), så OpenUserStatus parser ikke for de informationer og svaret indeholder ikke felter til data fra UserOptionalFields strukturen i ncip svaret.
Så det skal afklares om nogle lokalsystemer udleverer informationerne og hvilke felter de bruger til det, hvorefter en ny version af openUserStatus kan udvides til at indeholde disse information.

**Comment by DDBdrift** [comment]
Ifølge http://fbsudrulning.dk/wp-content/uploads/IFS0003-Cicero-NCIP-Specification-1.pdf så burde oplysningerne være tilgængelige:

5.1.3 Address Role Type
Context: User
	home Home address
	co C/O address

5.1.4 Address Type
Context: User	Values Content
	street address Physical address
	electronic mail address Email

5.2.1 User Element Type
Context: User
	Block Or Trap
	Date Of Birth
	Name Information
	User Address Information
	User Language
	Visible User Id

**Comment by fvsdbc** [comment]
Det er da super. Og, i hvilke ncip-felter placeres disse information, eller et eksempel på en ncip-response med disse felter udfyldt er endnu bedre. (ps. ved klik på fbsudrulnings linket, vises blot forsiden http://fbsudrulning.dk/ og ikke pdf-dokumentet)

**Comment by DDBdrift** [comment]
Sjov på FBS :-D Prøv http://fbsudrulning.dk/partner-bogen/ og kig efter 
NCIP Specifikation:
•Cicero NCIP Specification (08072016)

**Comment by fvsdbc** [comment]
Alt ser fint ud.. Så nogen skal lande en opgave om at lave en ny version af openUserStatus med disse felter. En testbruger med samtlige felter på et Cicero bibliotek, vil være en god hjælp til test - det tager vi udenfor github.

**Comment by DDBdrift** [comment]
Har tilladt mig at fjerne "Wont fix" label. Har I brug for hjælp til en FBS-låner??

**Comment by kkdbc** [comment]
jf. mailkorrespondance: udvidelse af openuserstatus, kan med fordel tages i projekt på RP17, hvor servicen foreslåes videreudviklet. Skal prioriteres.

**Comment by DDBdrift** [comment]
@kkdbc Vil du give KBP en beskrivelse? Så tager vi den sammen

**Comment by kkdbc** [comment]
det gør jeg

**Comment by BettinaAndersen** [comment]
OpenUserStatus er udvidet og implementeret på DÅP. REF: https://github.com/DBCDK/serviceprovider/issues/749
