### ISSUE TITLE
Gennemgående eksempel til intro [Ønske]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#699]
Der mangler et gennemgående eksempel med alle de data, som skal bruges ved genering af token (Client_? og User_? Samt ISIL)

**Comment by DDBdrift** [comment]
CSI@slks.dk har lavet et eksempel. Det bliver vedhæftet her ASAP

**Comment by kkdbc** [comment]
vi tager teksen fra smaug og lægger det ud på dåp i swagger dokumentationen.
