### ISSUE TITLE
MaterialeId og TitleID på debt entities i /Status/user [Ønske]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#702]
Det er ikke muligt at spore det enkelte materiale ud fra data.

```
"debt": [
      {
        "amount": "20",
        "currency": "DKK",
        "date": "2015-11-21T00:00:00.000Z",
        "author": "Kristín Marja Baldursdóttir",
        "title": "Kantate"
      }
```

**Comment by kkdbc** [comment]
Det kan kun udlevers fra FBS (brønd 3.5) Det sker allerde. Issue lukkes

**Comment by DDBdrift** [comment]
Har just test mod Roskilde. ID er IKKE med
{
  "statusCode": 200,
  "data": {
    "id": "CuOmQj0c4KihbuoMxbS89tOPSle7dkcb",
    "loans": [
      {
        "loanId": "651670012",
        "dueDate": "2017-07-03T00:00:00+02:00",
        "title": "Summer of love: the making of Sgt. Pepper",
        "author": "Martin, George"
      }
    ],
    "orders": [
      {
        "orderId": "normal:10243496",
        "status": "Active",
        "library": "DK-726500",
        "holdQueuePosition": "1",
        "author": "Deadmau5",
        "title": "4x4=12 (Joel Zimmerman)",
        "orderDate": "2017-03-28T00:00:00+02:00"
      },

**Comment by hrmoller** [comment]
@DDBdrift er det dig selv du har brugt i eksemplerne ovenfor eller er det monstro en testbruger vi kan få lov til at låne?

**Comment by hrmoller** [comment]
Afventer testbruger.

**Comment by DDBdrift** [comment]
@hrmoller @kkdbc Har just sendt testbruger pr. mail

**Comment by hrmoller** [comment]
@DDBdrift I svaret fra OpenUserstatus kan jeg godt se, at du har bøde på 20 kr. men jeg kan ikke se på hvilke materialer du har fået den. På min egen bruger får jeg en liste over de materialer jeg har fået bøde på.

**Comment by DDBdrift** [comment]
@hrmoller Har sendt dig mit login. Roskilde er på FBS

**Comment by DDBdrift** [comment]
@hrmoller Der er forskel på hvad CMS og DÅP leverer.

Her er svaret i DÅP 1 og 2 på /status/user/:
```
],
    "debt": [],
    "ddbcmsapi": "https://cmscontent.dbc.dk/"
  },
```
Dvs. jeg får pt IKKE bøden med !

i DDB CMS får jeg:

> Hobbitten - femhæreslaget
> •	Materialenummer: 5058012248
> •	Dato: 18. februar 2017
> •	Årsag:
> •	Beløb: 20,00 K

**Comment by hrmoller** [comment]
Interessant. Hvilken version af OpenUserstatus bruges i DDB CMS?

**Comment by hrmoller** [comment]
@DDBdrift det her er hvad jeg får på din bruger fra OpenUserstatus ang. bøder:
```
"fiscalAccount": {
    "totalAmount": {
      "$": "20",
      "@": "ous"
    },
    "totalAmountCurrency": {
      "$": "DKK",
      "@": "ous"
    },
    "@": "ous"
  }
```

**Comment by hrmoller** [comment]
Problemet ligger i OpenUserstatus og ikke OpenPlatform.

Efter aftale med Kurt gør jeg ikke mere lige nu men der vil blive set på sagen når den/de der har med OUS at gøre er tilbage fra ferie.

**Comment by hrmoller** [comment]
Der er blevet kigget på OpenUserinfo og det viser sig at Cicero ikke udlevere mere end det ovenfor beskrevne, så det må være Systematic der skal aktiveres her.
