### ISSUE TITLE
Change default opensearch to 4.5

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#703]

**Comment by hrmoller** [comment]
Kan det uddybes hvad forskellene er på nuværende default og 4.5?

**Comment by vibjerg** [comment]
Der bør ikke være nogen forskel i praksis, så vi har besluttet at skifte på biblo, og hvis det går godt ændrer vi default.

**Comment by vibjerg** [comment]
Default configurationen skal sættes til at køre op mod https://opensearch.addi.dk/b3.0_4.5/

**Comment by vibjerg** [comment]
fixed
