### ISSUE TITLE
Documentation: Logical connection between ClientID and CommunityID unclear

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#705]
> Getting startet
> 
> To get started with building a community, you will need a valid client and clientID, and the client needs to be configured with a valid community ID. To apply for access, contact https://kundeservice.dbc.dk/. A valid token is required for all requests.

Should read something like:
> ... you will need a valid **client_ID** and **Client_secret** to generate an access token.
> The **client_id** has to be mapped to the **community_id** by DBC. Please contact https://kundeservice.dbc.dk/ suppying the **Client_id** and name/ID of the community.

**Comment by kkdbc** [comment]
sætter ny tekst ind
