### ISSUE TITLE
Højere limit på /work og /recommend end 20 [Ønske]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#706]
```
{
  "statusCode": 400,
  "error": "limit must have a maximum value of 20"
}
```

**Comment by kkdbc** [comment]
Hvad er acceptabel limit? 
hvis vi istedet kun udleverer 1 pr. kald kan dåp parallelisere istedet?  
@DDBdrift

**Comment by DDBdrift** [comment]
100 / 128 Afhængigt af hvor rundt tallet skal være ;-)

**Comment by hyatt03** [comment]
Der ser ikke ud til at være begrænsning på /recommend.

**Comment by DDBdrift** [comment]
/recommend kan håndtere 1000+

/Work har i hjælpeteksten:
> You should at most look up 20 ids per API call.

/search svarer på [limit=1000:](https://openplatform.dbc.dk/v1/search?access_token=32272a2f1c836968a13ffcd0548e2fbb3e7f4a40&q=%22Nisse%22&limit=1000)
```
{"statusCode":400,"error":"limit must have a maximum value of 20"}
```

**Comment by hyatt03** [comment]
Limit er øget til 50 grundet begrænsning i OpenSearch.
