### ISSUE TITLE
Definition af alle returkoder [Ønske]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#710]
som 42, 117, 207, 500 (sic!)
Dette er sat på Community services, men ikke på resten af services.
De er desværre ikke selvforklarende.

**Comment by kkdbc** [comment]
positive og negative forventede udfald dokumenteres.

**Comment by vibjerg** [comment]
@DDBdrift kan du give eksempler på hvor disse returkoder opstår? 42, 117, 207

**Comment by DDBdrift** [comment]
/Search/search , /Order/availability osv:
Har feltet 
{
  "statusCode": 0,

Hvilke status koder kan der komme - og hvad betyder de
I Community er HTTP fejlkoden 500 beskrevet. Link til standardkoderne - og beskriv, hvis der er nogen andre returkoder, man kan få

**Comment by vibjerg** [comment]
@DDBdrift: Jeg spørger specifikt til de statuskoder som du har skrevet i issuet: 42, 117, 207. De giver ikke nogen mening, så derfor er jeg meget interesseret i, hvor de er opstået.

**Comment by DDBdrift** [comment]
Har fundet skriftstedet: https://opensource.dbc.dk/services/moreinfo

||||||
|---|---|---|---|---|
|imageSize | no | no | coverImage, backImage |Attribute containing information about the size of cover image. Possible values: thumbnail, detail, detail_48, detail_128, detail_256, detail_42, detail_117, detail_207, detail_500. **Number indicates the height of the image**.|

Burde nok fremgå af dokumentationen

**Comment by vibjerg** [comment]
Ok. Det har ikke så meget med returkoder/statuskoder at gøre, så jeg lukket dette issue, og flytter dokumentation af billedstørrelser til et nyt
