### ISSUE TITLE
VIP: Struktur på åbningstider [Ønske]

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#713]
På _/libraries_ kunne åbningstiderne godt standardiseres mere end bare en tekst fra bibliotekerne, så det giver mulighed for at se dags dato åbningstider og se ud i fremtiden.
Gerne med udgangspunkt i DDB CMS kalenderen. Åbningstider udstilles herfra i _ding_mobilesearch_.
De biblioteker som IKKE har DDB CMS + dette modul aktiveret, må så have teksten fra VIP

**Comment by kkdbc** [comment]
der forfindes en løsning til VIP (som strukturer data som regler inkl. undtagelser), som ikke er i brug dvs. indeholder ikke data fra bibliotekerne. Hvis dette skal prioriteres, skal vi kigge på dette modul igen. openagency kan dog ikke udlevere data, så det betyder udvidelser til denne service også. Forslag til alternativ løsning: integrer til google calendre.

**Comment by kkdbc** [comment]
@DDBdrift

**Comment by DDBdrift** [comment]
VIP ideen på hold for nuværende. Vi forsøger at udstille dem fra DDB CMS i stedet.
Men det løser ikke problemet for FFU bibliotekerne

**Comment by kkdbc** [comment]
lukkes jf kommentar fra ddb
