### ISSUE TITLE
Bedre dokumentation af billedstørrelser fra moreinfo ønskes

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#740]
||||||
|---|---|---|---|---|
|imageSize | no | no | coverImage, backImage |Attribute containing information about the size of cover image. Possible values: thumbnail, detail, detail_48, detail_128, detail_256, detail_42, detail_117, detail_207, detail_500. **Number indicates the height of the image**.|

Burde nok fremgå af dokumentationen

se #710

**Comment by KiraH** [comment]
Er nu med i dokumentationen under model for endpointet.
