### ISSUE TITLE
/Libraries: Agency kan ikke angives med ISIL nummer (DK-999)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#743]
Ved login SKAL der anvendes ISIL med DK- prefiks aht. FBS.
Ved hentning af biblioteksinfo i /libraries kan man ikke anvende prefiks.

`curl -X GET --header 'Accept: application/json' 'https://openplatform-stg.dbc.dk/v2/libraries?access_token=7ed498bd2ce64ad682a6f2710c2256ab&agencyIds=%5B%22DK-726500%22%5D'`

Testet på v. 2 stating

**Comment by DDBdrift** [comment]
@kkdbc: Testet i v.2 staging

Logger på Roskilde (FBS) med ISIL (DK-726500): 
1. 	Authentification returnerer token
2. 	status/user: svarer "statusCode": 200 og låner status returneres

Logger på Roskilde (FBS) med biblioteksnr (726500): 
1. 	Authentification returnerer token
2. 	status/user: "statusCode": 500, "error": "Agency authentication failed"

Konklusion: https://auth.dbc.dk/oauth/token videregiver Agency råt. 
Kan den auth sætte præfiks på biblioteksnr til FBS, således at vi altid kan få et gyldigt token med biblioteksnr.

**Comment by DDBdrift** [comment]
@kkdbc Lånerstatus indeholder ISIL-nummer - ikke biblioteksnr.
```
        "orders": [
            {
                "orderId": "normal:10243496",
                "status": "Active",
                "library": "DK-726500",
                "holdQueuePosition": "1",
                "creator": "Deadmau5",
                "title": "4x4=12 (Joel Zimmerman)",
                "orderDate": "2017-03-28T00:00:00+02:00"
            },
```

**Comment by kkdbc** [comment]
dåp skal sætte dk- på et agencynr, hvis det ikke har et i forvejen.
