### ISSUE TITLE
Handling of special characters in search queries

### ISSUE THREAD

**Issue by AndersFriisBrodsgaard** [DBCDK/serviceprovider#747]
phrase.titleSeries="Percy Jackson & olymperne" throws an error.

**Comment by hrmoller** [comment]
OpenSearch brokker sig over '&'-tegnet. Det skal nok erstattes af `&amp;` men om det er åben platform eller den enkelte klient der skal gøre det inden forespørgslen rammer ÅP må andre tage stilling til.

Personligt mener jeg ikke det er ÅP's opgave at rette forkerte forespørgsler, da det nemt ender i at den skal håndtere mange forskellige behov.

Jeg har en klump SOAP du kan fyre af mod OpenSearch hvis det er? Vil ikke poste her pga. credentials i SOAP-requesten.

Håndteringen af fejlen og beskeden der returneres fra ÅP kunne dog godt forbedres en smule.

**Comment by DDBdrift** [comment]
Udtrykket er korrekt CQL jvf. http://www.loc.gov/standards/sru/cql/spec.html


> charString2 | := | Double quotes enclosing a sequence of any characters except double quote (unless preceded by backslash (\)). Backslash escapes the character following it. The resultant value includes all backslash characters except those releasing a double quote (this allows other systems to interpret the backslash character). The surrounding double quotes are not included.

Svaret
```
{
    "statusCode": 400,
    "error": " additionalProperty \" olymperne\\\"\" exists in instance when not allowed"
}
```
må været en fejl i en parser

**Comment by fvsdbc** [comment]
Problemet opstår fordi & ikke må findes som data i xml.
Lavet et fix, som encoder det korrekt ifm. den soap-indpakning der finder sted.
