### ISSUE TITLE
Medtag (og udvid med) låneres navn, mail og adresse fra openUserStatus svaret

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/serviceprovider#749]
R17.02.02.01: OpenUserStatus udleverer flere lånerdata version 1.0
DÅP V2 skal bruge den ny version af openUserStatus og derfra videresende navn, mail og adresse. Det er ikke alle biblioteker der understøtter dette, så informationerne er ikke altid til stede i svaret fra openUserStatus.
Dokumentation på openSource.dbc.dk skal opdateres

**Comment by DDBdrift** [comment]
Dokumentationen i DÅP skal også opdateres
