### ISSUE TITLE
filter library opening times to reduce time and size of /library responses 

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#753]
Currently all opening times are stored in a mongodb (could be 25 years).

We have decided that for now only the next 90 days of opening times are returned. In the future this might be a parameter.

So the full document should be filtered to remove opening times before today and after today+90 days.

It is a good idea to cache the answer in the same mongodb, i.e. if the current cache entry is from today, just return it, otherwise recreate it from the full document.

This is a php/symphony task. 

Alternative solution: do it with a cron/jenkins/whatever job written in js/python/whatever and run something to filter all entries, say every night, and just return documents from that collection. This will require minimal php code changes.

**Comment by cboesgaard** [comment]
We solve it by having a cron job that updates a filtered version on a nightly basis with relevant entries (-y and +x days).

There might be an issue with the endpoint not being able to work with different collections for reads/writes. We might have to split the endpoint or extend the configuration to support two collections

**Comment by cboesgaard** [comment]
Napp would like to provide required opening days as a parameter. We can do that if we export say 90 days from the ws to the serviceprovider and make the serviceprovider do the filtering -- if we do that, it might be a good idea to change the dates from strings to dates for easier handling.

**Comment by cboesgaard** [comment]
First shot is here:
https://svn.dbc.dk/repos/skuffe/cbo/NAPP-SP-problem-2017-08/mongo-library-opening-hour-filter.py

Missing: tests ...and should be moved to a relevant place on github.

The only requirement is the debian package "python-dateutil".

Example:
./mongo-library-opening-hour-filter.py --src_db=cmsrestdb --src_col=Content --dst_db=openinghours_cache --dst_col=Content --days_before=0 --days_after=7

**Comment by BettinaAndersen** [comment]
Overflødig hvis http://platform.dandigbib.org/issues/2555 rulles ud.
