### ISSUE TITLE
håndtering af filialer

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#755]
SP skal understøtte at der ved forespørgsel på agency (væsen), udleveres samtlige filialer. Usecase er fx åbningstider. 

SP har løst dette, formentlig ved at tilføje nid'er og lave flere kald mod cmsws. Så indtil andet dukker op, betragtes dettes som løst. 

Fx giver denne request to filialer:
curl -X GET --header 'Accept: application/json' "https://openplatform-stg.dbc.dk/v2/library?access_token=$TOKEN&pretty=true&agency=123456&limit=20"

**Comment by BettinaAndersen** [comment]
Skal løses uden for DÅP
