### ISSUE TITLE
Napp skal benytte OS 4.5 (default version)

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#759]
Det ser ud som om at Napp bruger OS 4.3:
{
  "services": {
    "opensearch": "http://opensearch.addi.dk/b3.5_4.3/",
    "openuserstatus": "https://openuserstatus.addi.dk/1.5/"
  }
}
Napp skal sættes op til at bruge "default" OS-version

**Comment by KiraH** [comment]
Har sat Napp til OS 4.5, men da det er deres konfiguration mod b3.5 kan de ikke sættes til at køre default, da default konfigurationen er mod b3.0.
