### ISSUE TITLE
Rettelser til inline_models i dokumentation (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#761]
I inline_models er 
1. statusCode (integer), Bør angives som obligatorisk
2. "timings" er ikke angivet som valgfri

**Comment by rasmuserik** [comment]
Så er inline models blevet opdateret, og navngivet. Det ser ud til at `statusCode` allerede var obligatorisk, men timings manglede og er tilføjet.  Dette er nu inkluderet i pull request #862

**Comment by KiraH** [comment]
OK,
