### ISSUE TITLE
Swagger fejl: "malformed or unreadable swagger supplied" (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#762]
Swagger melder fejl på dokumentationssiden: https://openplatform-stg.dbc.dk/v2/#/
[ base url: /v2 , api version: 2.0.0 ]

> Error {...}
{"messages":["malformed or unreadable swagger supplied"]}

**Comment by cboesgaard** [comment]
There are multiple errors in the swagger spec. These can be debugged by getting the swagger file from the api (e.g. http://localhost:8080/v2/swagger.json) and checking it with the online editor at https://swagger.io/swagger-editor/ -> open source editor -> take me to the web version.

Semantic error at paths./community/comments/.get.responses.200.$ref
200 $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/.get.responses.default.$ref
default $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/.post.responses.200.$ref
200 $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/.post.responses.default.$ref
default $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/{id}.get.responses.200.$ref
200 $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/{id}.get.responses.default.$ref
default $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/{id}.put.responses.200.$ref
200 $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./community/comments/{id}.put.responses.default.$ref
default $refs cannot match any of the following: "*#/definitions*", "*#/parameters*"

Semantic error at paths./facets.post.responses.200.schema.properties.data.example.type
"type" should be a string

Semantic error at paths./facets.get.responses.200.schema.properties.data.example.type
"type" should be a string

**Comment by cboesgaard** [comment]
The swagger file kind of lives here I guess:
doc/spec.yaml
doc/specs/

**Comment by cboesgaard** [comment]
Part of solving this issue should be a readme in doc or doc/spec describing how these files play together.
