### ISSUE TITLE
Dokumentation af GET /availability (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#765]
> GET /availability	

bør tilføjes beskrivelsen:

> Get information about an items delivery status

Implementeringsnoten kan rettes til:

> Get information about an items delivery status (can be ordered / are available) for the currently logged in user at a specific library.

Bør eksemplificeres hvordan man afgør om materialet er:
1. Tilgængeligt (hvis/hvornår) ["expectedDelivery":]
2. Kan bestilles ["orderPossible": true]
3. Kan hjemlånes ["willLend": true]

Holdingstatus burde rettelig være ”**Availability**”, da beholdningsoplysninger ikke indgår i svaret – kun status på bestilling.

**Comment by rasmuserik** [comment]
Ser ud til at `expectedDelivery` også mangler i modellen.

**Comment by rasmuserik** [comment]
Tænker at rette resultat-API'et så `expectedDelivery`/`willLend` ikke ligger inde i et `holdingStatus` objekt.

**Comment by rasmuserik** [comment]
Har lavet en pull-request, der opdaterer API'et, samt dokumenterer `expectedDelivery`, `willLend` og `orderPossible`.

**Comment by KiraH** [comment]
testet OK
