### ISSUE TITLE
Dokumentation af GET /events (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#766]
Ændring til dokumentation:
- Modelbeskrivelse mangler. 
- Data er obligatorisk. 
- I data er access_token obligatorisk. 
- Agency er obligatorisk.
```
inline_model_6 {
statusCode (integer),
data (Inline Model 1, optional),
errors (Array[Inline Model 2], optional)
}
Inline Model 1 {}
Inline Model 2 {}
```

**Comment by rasmuserik** [comment]
> Ændring til dokumentation:
> - Modelbeskrivelse mangler. 

Skyldes så vidt jeg ved, at der ikke er nogen modelbeskrivelse for den underliggende service / ddbcms-modul. Jeg kan ihvertfald ikke finde denne, - men hvis der er et link til denne(?), vil jeg opdatere modelbeskrivelsen hurtigst muligt.

> - Data er obligatorisk. 

Jeg mener kun, at data returneres, hvis statusCode er 200 (at der ikke forekommer fejl), - og ellers er der en fejlbeskrivelse i errors. 

> - I data er access_token obligatorisk. 

Jeg kan ikke gennemskue hvor `access_token` er i `data`, - kan denne del af issuet uddybes?

> - Agency er obligatorisk.

Har tjekket koden, og kan se at `agency` er det bibliotek man er logget ind med, hvis det ikke bliver specificeret. Opdaterer dette i dokumentation.

**Comment by BettinaAndersen** [comment]
Datamodellen bør hænge sammen med applikations-ansvaret, hvilket er kommunikeret til DDB drift i mail.

**Comment by DDBdrift** [comment]
Dokumentation på CMS Content: https://cmscontent.dbc.dk/

**Comment by vibjerg** [comment]
dokumentationen på https://cmscontent.dbc.dk/ beskriver så vidt jeg kan se ikke datamodelen på de underliggende niveauer. Den beskriver kun at man får et array af items retur.

**Comment by DDBdrift** [comment]
Oprettet hos DDB CMS [#3431](https://platform.dandigbib.org/issues/3431)
