### ISSUE TITLE
Dokumentation af data returneret af GET /library (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#767]
pickupAllowed = 0 betyder nej til bestillinger eller midlertidig lukket
Værdierne kommer fra VIP B – 1 – a og bør beskrives.

Eksempel bør udbygges:
```
{
  "statusCode": 200,
  "data": {},
  "errors": [
    {}
```

**Comment by KiraH** [comment]
Modellen er udbygget så der nu vises de muligheder der er mht returneret data.
