### ISSUE TITLE
Dokumentation af GET /work	(Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#768]
Dokumentation af GET /work	

Disse felter bør inkluderes i standard:
```
"coverUrlBack":{"@id":"mi:coverUrlBack"},
"coverUrlFull":{"@id":"mi:coverUrlFull"},
"coverUrlThumbnail":{"@id":"mi:coverUrlThumbnail"},
```
Og det bør angives at stierne KUN giver adgang til billederne i få minutter!
Bør specificeres at disse felter returnerer data:
```
"coverDataUrlBack":{"@id":"mi:coverDataUrlBack"},
"coverDataUrlFull":{"@id":"mi:coverDataUrlFull"},
"coverDataUrlThumbnail":{"@id":"mi:coverDataUrlThumbnail"},
```

Forskellen på:
```
            "identifierURI": [
                "https://ereolen.dk/ting/object/870970-basis:52087902"
            ],

```
Og 
```
hasOnlineAccess": [
                "https://ereolen.dk/ting/object/870970-basis:52087902",
                "https://ereolen.dk/ting/object/870970-basis:52087902"
            ]
```
Bør beskrives. Det vil være ofte anvendte data.

**Comment by rasmuserik** [comment]
Følgende skulle være løst via pull request #862 

> ```
> "coverUrlBack":{"@id":"mi:coverUrlBack"},
> "coverUrlFull":{"@id":"mi:coverUrlFull"},
> "coverUrlThumbnail":{"@id":"mi:coverUrlThumbnail"},
> ```
> Og det bør angives at stierne KUN giver adgang til billederne i få minutter!
> Bør specificeres at disse felter returnerer data:
> ```
> "coverDataUrlBack":{"@id":"mi:coverDataUrlBack"},
> "coverDataUrlFull":{"@id":"mi:coverDataUrlFull"},
> "coverDataUrlThumbnail":{"@id":"mi:coverDataUrlThumbnail"},
> ```

**Comment by KiraH** [comment]
Er nu dokumenteret under model i beskrivelsen af endpointet.

**Comment by DDBdrift** [comment]
Er dog lidt ked af formuleringen: "will only work for a limited amount of time."
24 timer?

**Comment by rasmuserik** [comment]
Jeg tjekker op på det her, og opdatere formuleringen.

**Comment by rasmuserik** [comment]
Ja, den vil virke i 24 timer, - retter formuleringen. 

(i praksis mellem 24-48 timer, men det er en implementeringsdetalje)
