### ISSUE TITLE
Normalisering af AgencyID (og BranchID) 

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#769]
GET /events	- Agency ID to fetch content for	query	**integer**
GET /library	- Agency ID to fetch content for	query	**integer**
GET /news	- Agency ID to fetch content for	query	**integer**

Øvrige endpoint har agencyId og branchId som **Array[string]**
Rettes konsekvent til Array[string] på alle endpoints

**Comment by cboesgaard** [comment]
The CMS backend supports only requests for one agency at a time, i.e. a change to support multiple agencies in the SP api will require a new backend (+ api changes in request and response to support marking of multiple agencies and their corresponding results).

The fix only changes integer to string, not support of multiple agencies.

**Comment by cboesgaard** [comment]
This is now running on: https://openplatform-stg.dbc.dk/v2.
