### ISSUE TITLE
Normalisering af returdata: strenge eller lister (Staging v.2)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#770]
GET /recommend - Data returneret er formateret som strenge:
```
"data": [{
"pid": "870970-basis:28511663",
"title": "Journal 64 : krimithriller",
"creator": "Jussi Adler-Olsen"
}, 
```

hvor data search og work er formateret som lister:
```
"data": [{
"pid": ["870978-artikel:65825538"],
"title": ["Lille Ole! lille Ole!"],
"acIdentifier": ["65825538|870978"],
"date": ["1907"],
"extent": ["S. 385"],
"workType": ["other"]
},
```

Skal normaliseret konsekvent

**Comment by rasmuserik** [comment]
Årsagen til at metadata har forskellig "normalisering" er, at det er forskellige metadata:

- `/recommend` indeholder nogle cachede metadata, som er hurtige at få, og kan være praktiske at få med, men ikke nødvendigvis er den aktuelle værkinformation. Og ditto for `/rank`, samt `/suggest` på titel. 
- `/work`, og `/search` returnere den fulde værkinformation fra brønden.

Jeg har netop implementeret kode, som gør at `/recommend` returnerer metadata som lister a la `/work`, som foreslået, (ligger i pull-request #814) - jeg er dog ikke sikker på at dette er den rigtige løsning. Et bedre bud ville måske være at recommend/rank per default kun returnerer pid'erne og vægningen for materialerne så dette ikke er kilde til forvirring?

**Comment by DDBdrift** [comment]
Jeg har lidt svært ved at se, hvor forvirringen skal kunne opstå? Det er jo ikke sådan, at man forventer det fulde værk retur fra `/rank` ?! Data som `title` og `creator` burde jo ikke ændre sig løbende.
Udgangspunktet her er at to forskellige endpoints returnerer data på to forskellige måder. 
Hvis `/rank` kun returnerer en ordnet liste med pid'er, så skal der efterfølgende laves opslag i `/work` for at kunne vise simple data som `title` og `creator`. Det vil give en væsentlig performance forringelse med ekstra kald.

**Comment by rasmuserik** [comment]
Data fra recommender etc. kan sagtens pakkes ind som lister, så det gør jeg bare.

Jeg synes blot, at det er forvirrende fordi, `creator` og `title` er interne data i recommenderen, og ikke nødvendigvis matcher værkdata eksakt. Eksempel: `creator` er en vistnok enkel tekststreng i recommenderen, der lavet ud fra værkdata, også selvom der er flere forfattere. I eksemplet herover er `title`  "Journal 64 : krimithriller", hvorimod de i brønden blot er "Journal 64". Dette skylde implementationsdetaljer omkring recommenderen, som jeg ikke har det fulde overblik over.

**Comment by BettinaAndersen** [comment]
Overvejelserne blev diskuteret i dag til DÅP-møde. Konklusionen er forsat at datastrukturen skal ensrettes, dvs. lister. Der skal indsættes en kommentar om at /recommend ikke returnerer den fulde værkinformation, eks. én creator.

**Comment by rasmuserik** [comment]
Tilføjet `fixed` label i stedet for at lukke issue, når det er implementeret.

**Comment by KiraH** [comment]
testet OK i v3.

**Comment by DDBdrift** [comment]
"val" er stadig ikke en liste.
```
    {
            "creator": [
                "Rune Fleischer"
            ],
            "val": 0.2737536614150203,
            "title": [
                "Otto på festival"
            ],
            "pid": [
                "870970-basis:50936163"
            ]
        },
```

**Comment by rasmuserik** [comment]
Det var et bevidst designvalg fra min side at `val` ikke er et array, i modsætning til de bibliografiske metadata, - netop for at understrege, at `val` er vægten for anbefalingen i forhold til forespørgslen, og ikke egentlige metadata. Samme materiale har forskellig `val` afhængigt af hvilke materiale, materiale der er i forespørgslen.

Hvis vægtningen `val` skal være et array, på samme måde, som de bibliografiske metadata, kan jeg sagtens rette dette, men vil gerne have bekræftet at dette ønskes. @DDBdrift: Bekræft, at I faktisk ønsker, at resultat-vægtningen i forhold til forespørgslen, skal returneres på samme måde som materialets metadata (så retter jeg dette)?

**Comment by DDBdrift** [comment]
Vil gerne have ensrettet til array aht aftagerne

**Comment by KiraH** [comment]
Så er val også array.
