### ISSUE TITLE
Bug/regression in work-endpoint

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#774]
When fetching `coverUrl`s through the `/work` endpoint, it returns twice the number of objects requested. The added objects are empty (or apparently a copy of the previous object, if only one pid is requested).

- https://openplatform.dbc.dk/v1/work?pids=[%22870970-basis:22893645%22,%22870970-basis:29754519%22]&fields=[%22coverUrlThumbnail%22]&access_token=dd15daa92d9be303063ad98633856baed0619361
- https://openplatform.dbc.dk/v1/work?pids=[%22870970-basis:22893645%22]&fields=[%22coverUrlThumbnail%22]&access_token=dd15daa92d9be303063ad98633856baed0619361

Also: The result from coverUrlThumbnail, has changed schema from `//` (both http and https) to `https://`, breaking existing applications. (And the http resource still exist, - it is just the result from the service that has changed)

Both of these broke [Generiske Forsider](http://platform.dandigbib.org/projects/generiske-forsider)-projektet in different ways.

**Comment by KiraH** [comment]
Fejlen er rettet i openplatform v2.
