### ISSUE TITLE
Changes in API structure from v.1 to v. 2

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#775]
### Community added
Community service contains endpoints for handling user profiles and user generated content.

- [Guide](https://github.com/DBCDK/serviceprovider/tree/master/doc/community)
- [Endpoints](https://openplatform.dbc.dk/v2/#!/Community)

### expose images from cms ws (returned url part) #752 
The backend (CMS) returning the url (e.g. files/725300/6c87a7b175d886f2107b6195832ce955f18e2c72.jpeg)  returns a correct valid url.

### Medtag (og udvid med) låneres navn, mail og adresse fra openUserStatus svaret #749 
Lånerstatus udvidet fra
```
{
  "statusCode": 200,
  "data": {
    "id": "U2VydmljZVByb3ZpZGVy",
    "library": "710100",
    "loans": [
```
til
```
{
    "statusCode": 200,
    "data": {
        "id": "U2VydmljZVByb3ZpZGVy",
        "name": "Låners Navn",
        "address": "Låners adresse",
        "postalCode": "4000",
        "mail": "noone@nowhere.com",
        "loans": [],
        "orders": [
```

### /Libraries: Agency kan ikke angives med ISIL nummer (DK-999) #743 
Agency bør altid angives som ISIL-nummer (DK-999). Prefiks "DK-" bliver automatisk tilføjet

### Normalisering af AgencyID (og BranchID) #769 

> GET /events - Agency ID to fetch content for query integer
> GET /library - Agency ID to fetch content for query integer
> GET /news - Agency ID to fetch content for query integer
> 
> Øvrige endpoint har agencyId og branchId som Array[string]
> Rettes konsekvent til Array[string] på alle endpoints

> changed agency type to string #771 

### /user mangler indhold i "debt" (Staging v.2) 760

Testet MED gebyr som oprindeligt eksempel:
```
"debt": [
            {
                "amount": "20",
                "currency": "DKK",
                "date": "1970-01-01T00:00:00+01:00",
                "title": ""
            }
        ],
```
og i Kbh UDEN mellemværende:
```
        "debt": [
            {
                "amount": "0",
                "currency": "DKK",
                "date": "1970-01-01T00:00:00+01:00",
                "title": ""
            }
        ],
```
Debt struktur returneres også selvom "amount" er "0".

### Højere limit på /work og /recommend end 20 #706
Bump limit to 50, this is the limit found in opensearch.

### Konsistens på navne i det returnede JSON. Fx. ‘creator’ og ‘author’ #685 
author should be creator #633 
Author konsekvensrettet til creator

### Normalisering af dato og tid til ISO-format  #682 

> Dato og tid skal leveres i ISO 8601 format:
>     Dato=YYYY-MM-DD
>     Tid=YYYY-MM-DDThh:mm:ss
> Eksempel:
>     "dueDate": "2016-04-16"
>     "date": "2015-11-21T00:00:00.000Z"

Rettet i v.1, men nye eksterne moduler KAN potentielt levere datoer i andre formater.

**Comment by cboesgaard** [comment]
Der er de ting med jeg kender til (+ mange flere), så jeg har ikke noget at tilføje.

**Comment by DDBdrift** [comment]
Flyttet til [Wiki](https://github.com/DBCDK/serviceprovider/wiki/changes-in-api-structure-from-v1-to-v2)
