### ISSUE TITLE
Udvidelse af API spec til at dække response-data

### ISSUE THREAD

**Issue by cboesgaard** [DBCDK/serviceprovider#777]
I forhold til at holde styr på ændringer mellem versioner og for at gøre platformen nemmere at bruge, så ville det give god mening at specificere indholdet af data i responses.

Jeg ved ikke hvorfor det historisk set ikke er gjort, der har nok været nogle overvejelser, men der hvor vi er i dag, der mener jeg at det bør gøres, medmindre der er meget gode argumenter for at lade være. Som Napp gav udtryk for, så er det ikke så fedt som aftager at arbejde mod noget med en udefineret respons, og det er dyrt hvis vi effektivt flytter alt validering og cornercases ud til dem der i fremtiden forhåbentlig skal lave et antal systemer mod OP.

Der er flere måder at starte på, fx kunne vi udvælge nogle endpoints der er baseret på bagender der er velspecificerede og så gå efter at påvirke bagenderne efterhånden som vi får de mere fuzzy bagender med.

**Comment by BettinaAndersen** [comment]
Håndteret i andre issues
