### ISSUE TITLE
Merging af pull request fra Inlead

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#778]
Efter aftale med DDB er vi blevet bedt om at merge denne rettelse:
https://github.com/DBCDK/mobilesearch_rest/pull/13

**Comment by fvsdbc** [comment]
Pull requestet er lukket for et døgn siden med teksten:

This is deprecated with ding2/ding2#808, handling this on the Drupal-side.

Så dette er fikset ved ikke at gøre noget.
