### ISSUE TITLE
opsætning af stg miljø til smaug+cmscontent

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#779]
Serviceproviderens stg miljø skal sættes op til at benytte smaug stg og dermed cms-content stg.

Databaserne fra både smaug og cms-content skal kopieres fra produktion til stg miljøet.

Ret dokumentation til DÅP v2.

**Comment by DDBdrift** [comment]
Husk at rette i dokumentationen!
https://openplatform-stg.dbc.dk/v2/ henviser stadig til https://auth.dbc.dk/oauth/token

**Comment by KiraH** [comment]
tjek, det må vi få rettet.

**Comment by KiraH** [comment]
Da koden til stg og drift er den samme kan jeg ikke ændre url'en i dokumentationen, men har tilføjet hvilken url der skal bruges til stagingmiljøet.
