### ISSUE TITLE
cmscontent i v2 returnerer ikke indhold

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#781]
Forsøger man at hive nyheder ud på f.eks. testbiblioteket 123456 fra DÅP v1 får man nyheder retur.

Forsøger man det samme i v2 returneres der ikke noget data.

agency blev rettet fra int til string mellem de 2 versioner, ved ikke om det kan være problemet.

**Comment by fvsdbc** [comment]
Det er præcis skift fra integer til string der giver problemet. Ved ikke hvad fixet så skal være, eller den der spørger skal lære at det nu er en string.

**Comment by fvsdbc** [comment]
Se #769

**Comment by cboesgaard** [comment]
Det er jo en api ændring (der er ønsket og burde være dokumenteret), så det er vel ikke et problem? Dog er det en bug, hvis v2 ikke returnere et fejl, hvis man forsøger at spørge med en int.

**Comment by fvsdbc** [comment]
Med integer i v2, returneres 
{
  "statusCode": 400,
  "error": "agency is not of a type(s) string"
}

**Comment by cboesgaard** [comment]
Så er det vel som det skal være!?

**Comment by KiraH** [comment]
Problemet er at der ikke returneres noget indhold, selv om der er indhold i cmscontent.

Sætter man agencyid i '' får man ikke en fejl, men får ikke noget indhold, kun:

{
  "statusCode": 200,
  "data": []
}

Hvor jeg i v1, med søgning mod den samme cmscontent får:

{
  "statusCode": 200,
  "data": [
    {
      "title": {
        "name": "Title",
        "value": "Hovedbiblioteket",
        "attr": []
      },
      "author": { 
       .....
       .....
       .....
    }
  ]
}

**Comment by KiraH** [comment]
OK, det virker hvis man bruger dobbletplinger.
