### ISSUE TITLE
/work - Samme forside på forskellige poster

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#782]
To forskellige titler får samme forside.

> curl -X GET --header 'Accept: application/json' 'https://openplatform.dbc.dk/v2/work?fields=%5B%22dcTitleFull%22%2C%22creatorAut%22%2C%22identifierURI%22%2C%22coverUrlBack%22%2C%22coverUrlFull%22%2C%22coverUrlThumbnail%22%5D&access_token=942a30c4ff7271c041eca4660db5485e58339009&pids=%5B%22870970-basis%3A51329465%22%2C%22870970-basis%3A51626702%22%5D'

```
{
  "statusCode": 200,
  "data": [
    {
      "dcTitleFull": [ "Da ost blev for alle : 100 års udvikling set fra Brørup Mejeri" ],
      "creatorAut": [ "Jørgen Burchardt (f. 1946)" ],
      "identifierURI": [ "https://ereolen.dk/ting/object/870970-basis:51329465" ],
      "coverUrlFull": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51329465&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ff7618fec7b6e781718e" ],
      "coverUrlThumbnail": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51329465&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=cd216b297385b8f30b04" ]
    },
    {
      "dcTitleFull": [ "Jul - det er en ordre! : 4 møgirriterende julefortællinger i 31 kapitler" ],
      "creatorAut": [ "Jesper Manniche (f. 1982-03-28)" ],
      "identifierURI": [ "https://ereolen.dk/ting/object/870970-basis:51626702" ],
      "coverUrlFull": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51329465&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=ff7618fec7b6e781718e" ],
      "coverUrlThumbnail": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51329465&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=cd216b297385b8f30b04" ]
    },
    {
      "coverUrlFull": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51626702&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=b7b15491ac44d1238eea" ],
      "coverUrlThumbnail": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51626702&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=390eac17f189c4dd6a7e" ]
    },
    {
      "coverUrlFull": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51626702&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=b7b15491ac44d1238eea" ],
      "coverUrlThumbnail": [ "https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51626702&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=390eac17f189c4dd6a7e" ]
    }
  ]
}
```

**Comment by fvsdbc** [comment]
Fejlen eksponeres af moreinfo/2.9 som leverer dupplerede svar tilbage - spørger man på 2 pid'er, kommer der 4 svar tilbage, hvor de 2 første er ens og de to næste også.
MEN, det eksponerer at DÅP vil fejle, såfremt moreinfo ikke leverer svarende i den rækkefølge som der spørges i - og det er der reelt ingen krav til.

**Comment by fvsdbc** [comment]
Men, skift til moreinfo/2.10 vil med det samme fjerne "fejlen"

**Comment by DDBdrift** [comment]
Så vil vi MEGET gerne skifte DÅP v.2 (prod) til moreinfo/2.9
Og gerne have en release dato med på beskrivelsen sammen med den fine End-of-life:
> End-of-life date for versions older than 2.10 is December 1, 2017
@KiraH Kan du trylle den?

**Comment by fvsdbc** [comment]
Har lavet et fix til DÅP v2 så det også virker mod moreinfo/2.9. Fixet håndterer også at moreinfo svarer i en anden rækkefølge end forespørgslen

**Comment by DDBdrift** [comment]
Prøver lige igen: Så vil vi MEGET gerne skifte DÅP v.2 (prod) til moreinfo/**2.10**

**Comment by fvsdbc** [comment]
Fixet i dåp v2 er stadig nødvendigt, da moreinfo er skiftet fra http til https og det tog koden ikke højde for.

**Comment by KiraH** [comment]
Jeg har rullet ændringen ud i produktion.

**Comment by DDBdrift** [comment]
Protokollen "https:" er forsvundet fra URL:
```
"coverUrlFull": [
        "//moreinfo.addi.dk/2.9/more_info_get.php?lokalid=51329465&attachment_type=forside_stor&bibliotek=870970&source_id=870970&key=f722a4a98db27240bbe9"
      ],
```

**Comment by fvsdbc** [comment]
Det er som i version 2.6, dvs. protokollen er der ikke. DÅP fjerner den. Det var et skift til https i moreinfo, som pludselig gjorde at protokollen dukkede på i 2.9 af moreinfo. 
Så rettelsen vedr. de forkerte forsider, rettede også den fejl (at kun http:, men ikke https: blev fjernet.
Så, hvis protokollen pludselig nu med tages, så vil andre produkter, som fx. biblo, skulle rettes før de kan sifte til version 2.9++

**Comment by fvsdbc** [comment]
Mht. 2.10 eller 2.9, sørger rettelsen for at begge kan benyttes, men 2.10, som er den nyeste, bør gerne bruges frem for 2.9

**Comment by DDBdrift** [comment]
Det er muligt, at det er fredag ... MEN
```
"coverUrlFull": [
        "//moreinfo.addi.dk/2.9...."
      ],
```
er IKKE en URL. OG den afviger fra både v. 1 og den v.2 som er i produktion. Derfor skal protokollen med.

Hvis biblo.dk eller andre laver løjer med strengen, så dem om det. OpenPlatform skal udstille en ÆGTE URL - og gerne den rigtige.

**Comment by fvsdbc** [comment]
Har revertet https: rettelsen, så det ikke fjernes. Må se hvad biblo og andre så gør.

**Comment by DDBdrift** [comment]
Biblo (og evt andre må rette til)
