### ISSUE TITLE
Uoverensstemmelse mellem /availability og /order

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#783]
pid er hhv. string og Array[string], hvilket ikke giver nogen mening.
Availability bør kunne håndtere et array

### GET /availability

Parameter | Value | Description | Parameter Type | Data Type
---|---|---|---|---
pid |   | pid of the work to order | query | ***string***

### GET /order

Parameter | Value | Description | Parameter Type | Data Type
---|---|---|---|---
pids |   | The pids of the material to order. Several pids can be given, for example if you want to order a book, but does not care which of the editions. Required, and only applicable to new orders when making a new order. | query | ***Array[string]***

**Comment by fvsdbc** [comment]
Hvis der kan spørges på mere end en pid, hvorledes skal det så påvirke resultatet. Skal det på en eller anden måde fortolkes til ét svar, eller, skal svaret blive til et array med et svar for hver pid der spørges på

**Comment by DDBdrift** [comment]
Oplagt som et array. Så kan klienten behandle svar som samme måde som fra søgning etc.

**Comment by fvsdbc** [comment]
Men, sammenlignes med /order, så er svaret der ikke er array, men i stedet er samlet ok eller ej.

Hvad enten det ene eller anden vælges, så får det konsekvenser for de som benytter v1 og der skal kodes noget om i logikken i serviceprovideren.

**Comment by fvsdbc** [comment]
Availability kalder internt 2 operationer: checkOrderPolicy fra openOrder og holdingsRequest fra openHoldingsStatus.
checkOrderPolicy kan godt tage flere pid'er, men svaret er så konsolideret, så der skal laves et kald pr. pid for at kunne levere pid-specifikke svar.
holdingsRequest kan tage flere pid'er og leverer et svar pr pid.

**Comment by DDBdrift** [comment]
Indrømmet - jeg forstår ikke helt svaret. Betyder det at checkOrderPolicy skal loope igennem listen?

**Comment by DDBdrift** [comment]
DDB ønsker at availability skal være et array med et svar for hver pid der spørges på. Loopet må evt. lægges ind i logikken.
