### ISSUE TITLE
/Order/Order - "SyntaxError: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#784]
Order fejler med en syntaksfejl

> https://openplatform-stg.dbc.dk/v2/order?access_token=c5c9b650e3eb645d4e3cf3a66eb328d8f597d44f&pids=%5B%22870970-basis%3A28758596%22%5D&library=%22725300%22

```json
Response Body
{
  "statusCode": 500,
  "error": "SyntaxError: Unexpected token < in JSON at position 0"
Unexpected token < in JSON at position 0"
}

```

**Comment by fvsdbc** [comment]
Fejlen opstår når der ikke angives en expires dato.

Fix lavet.

**Comment by fvsdbc** [comment]
Og, testbart her: https://openplatform-stg.dbc.dk/v2/

**Comment by DDBdrift** [comment]
Henter ny token og før svaret på staging:
```
{
    "statusCode": 401,
    "error": "invalid_token",
    "error_description": "The access token expired"
}
```

**Comment by fvsdbc** [comment]
Fik også expired med ovenstående token. Hentede et nyt og så gik det bedre. Men det er mod min egen version af v2. Mod v2 stg funker tokenet også, men her får jeg så service unavailable. Nok fordi der peges til en gammel test openorder - det finder vi ud af og retter i morgen. MEN, det skal kunne nå til service unavaiable, med et nyt token. Hvilket client-navn trækker du token fra - jeg er ikke så vild med at eksponere url'er med tokens, her i en offentlig git-repo

**Comment by DDBdrift** [comment]
@fvsdbc Ring lige til mig: 33733317

**Comment by DDBdrift** [comment]
Staging melder:
```
{
  "statusCode": 503,
  "error": "service_unavailable"
}
```
Produktion melder:
```
{
  "statusCode": 500,
  "error": "SyntaxError: Unexpected token < in JSON at position 0"
}
```

**Comment by DDBdrift** [comment]
/order/order svarer ved sletning af bestilling:
```
{
    "statusCode": 500,
    "error": "Agency authentication failed",
}
```

> curl -X GET --header 'Accept: application/json' 'https://openplatform.dbc.dk/v2/order?access_token=SLETTET&orderId=%22normal%3A16167251%22&delete=true'

**Comment by fvsdbc** [comment]
Det token du brugte, var det et med brugeridentifikation og bibliotek - et fra grant_type=passowrd

Beskedden er klar nok. Du har ikke rettighed til at slette bestillingen, men det anvendte token.

**Comment by DDBdrift** [comment]
Øh - DET svar forstår jeg ikke? Jeg opretter en bestilling fra en profil, der er logget ind med brugerID og Agency. Og derefter kan jeg ikke slette den igen?

```
curl -X GET \
'https://openplatform.dbc.dk/v2/order?access_token=SLETTET&pretty=true&timings=true&library=%22DK-726500%22&orderId=%22normal%3A16167251%22&delete=true' 
```
Ja brugeren er autentificeret med `Grant_type=password`

**Comment by fvsdbc** [comment]
Jeg har netop trukket et token med grant_type=password. Brugt det til at bestille en bog på København (hvor jeg bor), set at den dukkede op under reservationer. Lavet GET user med samme token, fundet orderId. Og igen med samme token, og det fundne orderID, slettet bestillingen.

library er ligemeget når der slettes, kun orderId behøves. Bibliotek, cpr og pin er givet via det token der bruges.

Så, jeg kan kun, som sidst, få det til at fungere. Kan du maile os hvad du prøver med, så vi kan debugge med det, for at se hvad det skyldes, at det fejler for dig: Der er dømt efterårsferie for mange af os, så med mindre andre kigger på det, så bliver det først i uge 43, at jeg kan se på det igen.

**Comment by fvsdbc** [comment]
Måske skulle det her over i et nyt issue. Overskriften er lidt misvisende.

**Comment by fvsdbc** [comment]
Og, "synderen" er openUserStatus, som bruger cancelOrderRequest, som via NCIP forsøger dette. 

Det fungerer, ikke underligt, mod København, men mod et cicero-bibliotek (har prøvet med greve), får man, helle ikke underligt, en fejl tilbage:

**Comment by fvsdbc** [comment]
Og, "synderen" er openUserStatus, som bruger cancelOrderRequest, som via NCIP forsøger dette. 

Det fungerer, ikke underligt, mod København, men mod et cicero-bibliotek (har prøvet med greve), får man, helle ikke underligt, en fejl tilbage:

SELECT laanertjek.address, laanertjek.password, vip_kat.ncip_renew, vip_kat.ncip_cancel, vip_kat.ncip_update_request, vip_kat.ncip_lookup_user, vip_kat.ncip_lookup_user_address, vip_kat.ncip_lookup_user_password FROM fjernadgang_andre, fjernadgang, laanertjek, vip_kat WHERE fjernadgang_andre.navn = 'bibliotek.dk1 AND fjernadgang_andre.faust = fjernadgang.faust AND fjernadgang.bib_nr = 735000 AND (laanertjek.type = 'ncip' OR laanertjek.type = 'ncipk') AND vip_kat.bib_nr = 735000 AND fjernadgang.laanertjekmetode_id = laanertjek.id_nr

**Comment by fvsdbc** [comment]
En tanke på vej på ferie: Er det agency kontra ISIL nummer som får det til at fejle? Jeg kunne slette bestillingen gennem openUserStatus ved at bruger ISIL nummer som agency. Bestilligen blev slettet, men svaret fra Cicero opfattes ikke optimalt. Så det ER samspillet mellem openUserStatus og Cicero der skal ses nærmere på.

**Comment by DDBdrift** [comment]
Kan god bestille med enten biblioteksnr eller ISIL nummer. 
Har testet annullering med forskellige kombinationer af biblioteksnummer og ISIL. Har testet både for væsen (Roskilde) og filial (Gundsømagle). Men får ved annullering samme fejl: "Agency authentication failed".
Burde kunne oprette og annullere med samme token

Undrer mig lidt over at ordrenummeret har dette format i /status/user:
`"orderId": "normal:16245917"`
Hvorfor optræder strengen "normal" i Id?

**Comment by fvsdbc** [comment]
OrderId indeholder to elementer: orderType og orderId. orderType skal være en af flg: 'Estimate', 'Hold', 'Loan', 'Non-returnable Copy', 'normal', 'Stack Retrieval'
Det er agency/isil-nummer problematikken, som får openUserStatus til at fejle. Laver et fix til openUserStatus, så den fikser at servicen tager agency som input, mens det bagvedliggende ncip, bruger isil-nummer.

**Comment by fvsdbc** [comment]
Og med rettelsen i openUserStatus, bliver bestillingen nu slettet. MEN, svaret fra cicero overholdet ikke ncip-standarden (UniqueUserId elementet i CancelRequestItemResponse mangler) og derfor sender openUserStatus en fejl videre til serviceprovideren, selvom bestillingen faktisk bliver slettet.

**Comment by fvsdbc** [comment]
Har fjernet tjekket i openUserStatus på (det manglende) UniqueUserId, og nu svarer openUserStatus "pænt" tilbage på cancelRequestItem.

Nogen må bede Cicero om at rette deres svar, hvorefter vi igen kan tjekke CancelRequestItemResponse's korrekthed.
Kræver at version 1.6.1 af openUserStatus sættes i drift og serviceprovideren skiftes til at bruge denne.

**Comment by fvsdbc** [comment]
Version 1.6.1 nu tilgængelig: https://openuserstatus.addi.dk/1.6.1/

**Comment by DDBdrift** [comment]
> /order/order/

forventer pickUpBranch i parametren "library" og ikke Agency. "library" bør være specifikt Agency som væsen eller Branch som filial. Her bør rettes til pickUpBranch (Også i dokumentationen)

Svaret er:
``` json
{
    "statusCode": 200,
    "data": {
        "status": "ok"
    }
}
```

Her mangler jeg en egentlig kvittering med:
1. orderId
1. agency
1. pickupBranch
1. orderDate
1. expireData

Jeg kan derfor ikke umiddelbart slette bestillingen igen uden at lave et opslag på lånerstatus
Fra /status/user fås:

```
{
	"orderId": "normal:16559675",
	"status": "Active",
	"pickUpAgency": "DK-726500",
	"holdQueuePosition": "1",
	"creator": "Fleischer, Rune",
	"title": "Otto møder en nisse",
	"orderDate": "2017-10-25T13:53:24+02:00",
	"titleId": "50936155"
}
```
pickUpAgency giver ikke den helt store mening, da det blot er det Agency der leverer status.
Bestillingen skal leveres til pickUpBranch (DK-726503), hvilket ikke fremgår.

Ang. orderId:

> OrderId indeholder to elementer: orderType og orderId. orderType skal være en af flg: 'Estimate', 'Hold', 'Loan', 'Non-returnable Copy', 'normal', 'Stack Retrieval'

Hvorfor er orderType ikke et selvstædigt felt?! 
```json
{
	"orderId": "16559675",
	"orderType": "normal",
	"status": "Active",
```

Hvad skal man så angive ved sletning af en bestilling? Er det med eller uden type?

Har testet med begge dele både ISIL og biblioteksnr, men alt bliver afvist

```
access_token:{{access_token}}
pretty:{{pretty}}
delete:true

orderId:normal:16559543
library:"726500"
//"error": "Agency authentication failed"
//
//orderId:"16559543"
//library:"726500"
//"error": "Agency authentication failed"
//
//orderId:"16559543"
//library:"DK-726500"
//"error": "Agency authentication failed"
//
//orderId:16559543
//"error": "orderId is not of a type(s) string"
//
//orderId:normal:16559543
//library:726500
//"error":"library is not of a type(s) string"
//
//library:DK-726500
//"error":"Agency authentication failed"
//
//library:DK-726503
//"error":"Agency authentication failed
```

**Comment by fvsdbc** [comment]
Har ændret en smule så bestilling, lånerstatus og cancelOrder nu alle fungerer hvad enten tokenet er trukket med agency som 123456 eller DK-123456. Det kræver som tidligere skrevet at man bruger openUserStatus 1.6.1, men det bør være rettet, jvf #787 

De resterende ting hører nok mere hjemme i et nyt issue, som omhandler ændringer i api'et. Der er ikke noget galt med forslagene. Et normalt brugsscenarie er dog nok at man ikke skal bruge ordre-id'et efter en bestilling, da det sjældent forekommer at man bestiller noget for deretfer at slette det med det samme. Normalt vil ændring/sletning af bestliing forekomme efter en lånerstatus operation. Ifm. test, kan det dog være meget nyttigt.

**Comment by DDBdrift** [comment]
Testet i produktion og staging

```
access_token:{{access_token}}
pretty:{{pretty}}
delete:true
orderId:"16559543"
library:"DK-726500"
```
giver svaret:
```
{
    "statusCode": 200,
    "data": {
        "deleted": true,
        "orderId": "16559543"
    }
}
```
Så jeg tror, at vi lukker denne sag.
De resterende bliver oprettet som selvstændige sager
