### ISSUE TITLE
/order/availability - svarer altid willLend: false

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#786]
Selvom jeg er logget på som lokal låner og materialet står på hylden får jeg konsekvent svaret

```json
{
    "statusCode": 200,
    "data": {
        "holdingStatus": {
            "willLend": false
        },
        "orderPossible": true
    }
}
```
Testet med

> 870970-basis:52462533
> Fugleværnsfonden : for fugle, for folk og for fremtiden
> Af Jan Skriver (2016)

i Roskilde.

**Comment by fvsdbc** [comment]
Har prøvet mod kbh (med mig selv som låner) med flg. resultat:

{
  "statusCode": 200,
  "data": {
    "holdingStatus": {
      "willLend": true,
      "expectedDelivery": "2017-11-25T00:00:00+01:00"
    },
    "orderPossible": true
  }
}

Og mod Lejre med den test-låner vi har der med flg. resultat:

{
  "statusCode": 200,
  "data": {
    "holdingStatus": {
      "willLend": true,
      "expectedDelivery": "2018-04-25T00:00:00+02:00"
    },
    "orderPossible": true
  }
}

Så, det ser ud til at fungere med de to. Jeg har for hver af dem, trukket et grant-type=password token, først.

**Comment by fvsdbc** [comment]
Muligvis har du brugt et "almindeligt" token, som ikke indeholder bibliotek og brugerinfo. Det afvises ikke, men giver præcis det samme du får.

**Comment by DDBdrift** [comment]
Både staging og prod giver nu: "willLend": true,
Jeg har ikke brugt andre grant_types end password jf. eksemplerne på https://openplatform.dbc.dk/v2/#/
