### ISSUE TITLE
Skift til OpenUserStatus 1.6.1

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#787]
Grundet ændringer i forhold til Order.
Ref: https://github.com/DBCDK/serviceprovider/issues/784

**Comment by KiraH** [comment]
Der er nu skiftet så DÅP stg kører med openuserstatus 1.6.1.

Vil @DDBdrift teste på stg før vi kører det ud i produktion?

**Comment by DDBdrift** [comment]
Selve udrulningen ser OK ud. Fejl tilføjes  #784
