### ISSUE TITLE
Oprettelse af lukket github til deling af tests

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#793]
Vi skal kunne dele tests med DDB (+ evt. andre). Det kunne fx være i lukket github-repo, med dir for hver test der som minimum indeholder:
 request.json eller curl line

Men også gerne:
respons.json
readme med fx url og evt. token

**Comment by KiraH** [comment]
done

**Comment by DDBdrift** [comment]
Hvad er "done" ? Og hvor?

**Comment by DDBdrift** [comment]
Jeg kan stadig ikke se den. Vil I tilføje mig - og gerne sende en mail
