### ISSUE TITLE
/renew returnerer ikke returnDate i svaret

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#794]
Ved et succesfuld kald til  /renew fortæller specifikationen, at der skal returneres loanId og returnDate, returnDate kommer dog aldrig med i svaret.

@DDBdrift kan vi tilføje denne, så svaret passer med specifikationen, uden at skabe problemer?

**Comment by DDBdrift** [comment]
Ja - vi kan godt udvide med ekstra information. Dette ønske gælder også for /order/order (se #784)

**Comment by fvsdbc** [comment]
Fixed i V2

**Comment by KiraH** [comment]
Når jeg forsøger at forny et lån får jeg:

{
  "statusCode": 500,
  "error": "Unknown item"
}

Er det fordi der skal være et loanId med? I så fald burde feltet være obligatorisk.

**Comment by KiraH** [comment]
Der returneres nu både loanId og returndate. Jeg lukker denne og oprettet kommentaren om loanId herover som nyt issue.
