### ISSUE TITLE
/order/order mangler data i svar

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#795]
> /order/order/

Svarer:
``` json
{
    "statusCode": 200,
    "data": {
        "status": "ok"
    }
}
```

Her mangler jeg en egentlig kvittering med:
1. orderId
1. agency
1. pickupBranch
1. orderDate
1. expireData

Jeg kan derfor ikke umiddelbart slette bestillingen igen uden at lave et opslag på lånerstatus

**Comment by DDBdrift** [comment]
Svar fra Bettina: 
Dette er en udvidelse som kombinerer to services. 
Derudover går der tid før bestillingen er i lokalsystemet, så der kan ikke umiddelbart sendes tilbage.

**Comment by DDBdrift** [comment]
Det essentielle her er muligheden for at spore en bestilling i lånerstatus. Er der en ordreid fra bestilsystemet der kan spores på?

**Comment by fvsdbc** [comment]
OpenOrder laver bestillinger til ORS-systemet, og der nummer openOrder returnerer er et id til det system. ORS håndterer bestillingen senere. Oftest meget hurtigt derefter, men hvis ORS er belastet, kan der gå længere tid. ORS afleverer bestillingen til lokal-systemet, hvorefter bestillingen bliver synlig for openUserStatus, hvor lokalsystemts orderID kan ses og, derefter bruges til at "manipulere" med bestillingen.
Dvs. det bestil-ID som openOrder leverer tilbage, kan udelukkende bruges til at spore bestillingen i ORS-systemet (og vil kunne ses i netpunkt's bob-system, som "snakker" med ORS-systemet)

**Comment by DDBdrift** [comment]
Vil gerne have national ordre-id tilbage. ( Kan kun bruges til national annullering) Kan ikke bruges til opslag i lånerstatus.
Undersøges om /status/user returnerer lokalt eller nationalt orderId

**Comment by rasmuserik** [comment]
Har netop tilføjet en pull-request, #835, som inkluderer ORS orderId, i feltet `orsId`, hvilket er det, som Den Åbne Platform får tilbage fra det undeliggende bestil-system.
