### ISSUE TITLE
/status/user - OrderId indeholder type

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#798]
Fra /status/user fås:

```
{
	"orderId": "normal:16559675",
	"status": "Active",
	"pickUpAgency": "DK-726500",
	"holdQueuePosition": "1",
	"creator": "Fleischer, Rune",
	"title": "Otto møder en nisse",
	"orderDate": "2017-10-25T13:53:24+02:00",
	"titleId": "50936155"
}
```

> OrderId indeholder to elementer: orderType og orderId. orderType skal være en af flg: 'Estimate', 'Hold', 'Loan', 'Non-returnable Copy', 'normal', 'Stack Retrieval'

orderType  skal være et selvstædigt felt
```json
{
	"orderId": "16559675",
	"orderType": "normal",
	"status": "Active",
```

**Comment by BettinaAndersen** [comment]
Sat på pause, da antagelsen var at 'Renew' og 'Cancel' benyttede det samlede "orderid" (med type). Dette er dog ikke tilfældet for 'Renew'. Opsplitningen ønskes derfor fortsat.

**Comment by DDBdrift** [comment]
Lige en lille rettelse: `orderId` returneres af `/status/user` og `/order/order` . Den gives som parameter til `/order/order`  for at slette.
`/status/renew` er kun fornyelse af lån og tager derfor ikke `orderId` fra reserveringer.

**Comment by rasmuserik** [comment]
Har nu implementeret at orderType er et selvstændigt felt i pull-request #832 

Tilsvarende er endpointet for at slette ordre også opdateret så ordre-identifieren er kombinationen af orderId + orderType, i stedet for blot en enkelt parameter.

Jeg vil lige bemærke, at årsagen til at orderType ikke var et selvstændigt felt, var et designvalg om at gøre det lettere, at udvikle op mod den åbne platform. I.e. at der var en enkelt identifier for ordre, når de skulle slettes (eller opdateres), således at applikationsudviklere ikke skulle bekymre sig om / skrive kode i app'en, der håndterede, at identifieren faktisk bestod at to dele.

**Comment by rasmuserik** [comment]
Closed da den ønskede ændring er merget nu.

**Comment by KiraH** [comment]
testet OK
