### ISSUE TITLE
https://openplatform.dbc.dk/v2/guide.html henviser til v. 1

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#799]
> This introduction to getting started with the open platform is online on: https://openplatform.dbc.dk/v1/guide.html#client_id:client_secret. Supply your client_id and client_secret in the url hash, to make the examples work.
> 
> The api-documentation is https://openplatform.dbc.dk/v1/.
> 
> 
> JavaScript API
> 
> To use the open platform from a browser, load https://openplatform.dbc.dk/v1/dbc_openplatform.min.js, with a <script>-tag, or in a similar way. Then the dbcOpenPlatform object will be available. Do not cache this JavaScript library indefinitely, as the underlying implementation may change if we change the transport protocol.

Bør generelt ikke henvise til en specifik version men til den generiske side

>https://openplatform.dbc.dk/v1/
rettes til
>https://openplatform.dbc.dk/

**Comment by KiraH** [comment]
Er du sikker på det er det I vil have? 

_Bør generelt ikke henvise til en specifik version men til den generiske side

    https://openplatform.dbc.dk/v1/
    rettes til
    https://openplatform.dbc.dk/_

Url'en uden version redirigeres til den nyeste produktions version, så går du f.eks. ind på guiden under version 1 vil et link uden version redirigeres til api'et for version 2, og det er måske lidt forvirrende.

**Comment by DDBdrift** [comment]
Jeg forstår godt din betænkelighed, men dette er netop v.2 guiden, som henviser til v.1, hvilket er helt galt.
Der bør altid henvises til nyeste version. Alternativt skal versionsnummeret holdes opdateret.

**Comment by KiraH** [comment]
Ja, det skal selvfølgelig rettes, men eftersom der også er url'er med versionsnummer midt i, som vi ikke bare kan fjerne er vi nødt til at tilpasse url'erne alligevel og så kan vi lige så godt lade alle url'er passe til den version, hvis guide man er gået ind på.

Vi opretter et issue på at få rettet versionsnumrene i url'erne automatisk :)

**Comment by KiraH** [comment]
ligger nu på stg

**Comment by DDBdrift** [comment]
Super. Så skal den "blot" rettes i prod og v.3 stg også.
http://www.danbib.dk/broend3_soeg.
I øvrigt henviser https://openplatform-stg.dbc.dk/v2/guide.html med et link til CQL dokumentation på http://www.danbib.dk/broend3_soeg - som ikke findes. 
Bør nok rettes til http://www.danbib.dk/sogning-bronden

**Comment by KiraH** [comment]
Rettelser i prod kommer automatisk når der deployes til prod. Kigger på at få rettet i v3

**Comment by KiraH** [comment]
Nu rettet på v3. og linket til danbib er også rettet og kørt i prod på v1 og v2.

**Comment by DDBdrift** [comment]
Er ikke rettet på: https://openplatform.dbc.dk/v3/guide.html

**Comment by KiraH** [comment]
Det er fordi den ikke er kørt ud i produktion. Officielt har vi ikke noget produktionssite på v3 endnu, her er det stg sitet der er det benyttede indtil v3 kommer i drift. Til den tid vil alle rettelser selvfølgelig være kommet derud.
