### ISSUE TITLE
Ændring af master branch til udviklingsbranch og navngivne branches til idriftsatte versioner.

### ISSUE THREAD

**Issue by vibjerg** [DBCDK/serviceprovider#801]
1. Der skal laves en v1 branch ud fra master, og udrulning af v1 skal flyttes til denne branch.
2. v2.x.x branchen skal merges ned i master. v2.x.x og omdøbes til v2.0. Udrulning af v2 skal ske fra denne branch. 

3. Herefter vil masterbranchen være udviklingsbranch for v3 features.

**Comment by KiraH** [comment]
Done
