### ISSUE TITLE
/search/search fejler på http/https ved cover felter

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#802]
Fejl 500 ved hent af cover med kald til moreinfo. Testet med:
```
curl -X GET \
  'https://openplatform-stg.dbc.dk/v2/search?access_token=SLETTET&pretty=true&timings=true&q=%22adler%22%20and%20%22selfies%22&offset=0&limit=20&sort=rank_verification&fields=%5B%22titleFull%22%2C%20%22creator%22%2C%20%22pid%22%2C%22coverUrlFull%22%2C%22coverDataUrlThumbnail%22%5D' 
```
```
{
    "statusCode": 500,
    "error": "Error: Invalid URI \"http:https://moreinfo.addi.dk/2.9/more_info_get.php?lokalid=52559316&attachment_type=forside_lille&bibliotek=870970&source_id=870970&key=847778c26aad6c0c0a3a\""
}
```

**Comment by DDBdrift** [comment]
Problemet kommer fra "coverDataUrlThumbnail"

**Comment by BettinaAndersen** [comment]
Det ser ud til at vi ikke er skiftet helt over på MoreInfo 2.10? Det bør vi snarest.

**Comment by vibjerg** [comment]
Problemet med coverDataUrlThumbnail  bør allerede være løst i version 3

**Comment by KiraH** [comment]
Jeg har nu skiftet til moreinfo 2.10 og man får nu ikke længere en fejl hvis man forsøger at hente cover med den request der er sendt med i issue'et.

**Comment by rasmuserik** [comment]
Efter at #789 er merget, burde denne være løst.

**Comment by BettinaAndersen** [comment]
Skal også rettes i version 1 og 2.

**Comment by rasmuserik** [comment]
@KiraH @BettinaAndersen så skulle denne være backported til v1 og v2

**Comment by KiraH** [comment]
testet OK

**Comment by DDBdrift** [comment]
Det er kun rette på de tre staging versioner. Ikke i prod

**Comment by KiraH** [comment]
Nu i produktion på v1 og v2.
