### ISSUE TITLE
stg miljø til version 3

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#803]
Der skal oprettes et staging miljø til version 3.

- Opret pipeline

- Opsæt konfiguration

- IT skal lave proxy opsætning til ny version

- Staging skal være tilgængelig udefra

- Der skal oprettes en ny branch, så hver version har sin egen branch

- Evt. tilretning af de andre pipelines, hvis der ændres på branchnavn for disse.

Accept: 

- Når der pushes kode til 3.x branch, testes og bygges koden og deployes ud på nyt stagingmiljø.

- Det nye stagingmiljø skal kunne tilgås udefra.

**Comment by KiraH** [comment]
Stg site til version 3 skulle nu være tilgængeligt på:
https://openplatform-stg.dbc.dk/v3/

Vil @DDBdrift teste I kan tilgå denne?

**Comment by KiraH** [comment]
Jeg lukker denne.

**Comment by DDBdrift** [comment]
Sorry. Den smuttede for mig. Kan tilgå og har testet med user status
