### ISSUE TITLE
endpoint renew fejler ved kald uden loanId

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#805]
Når jeg forsøger at forny et lån får jeg:

{
"statusCode": 500,
"error": "Unknown item"
}

Enten skal loanId gøres obligatorisk eller også skal servicen kunne håndtere at man kalder uden loanId. Underliggende service fornyer alle lån, hvis den kaldes uden loanId.

**Comment by DDBdrift** [comment]
Den skal naturligvis forny alle lån
@KiraH Godt set!

**Comment by fvsdbc** [comment]
openUserStatus (renewLoan) kræver at der er et eller flere loanId(s), så det er ikke muligt at forny alle lån ved at udelade loanId. NCIP RenewItem, som sendes mod det aktuelle bibliotek, vil have netop et itemId, så openUserStatus sender en NCIP RenewItem for hvert itemId der gives. 

Eftersom klienten med rimelig sandsynlighed har lavet et opslag for at vise brugerens lån, så har klienten derved allerede samtlige itemId's, der skal bruges for at forny alt.
For at kunne lave en "blind" forny alt funktion, skulle openUserStatus lave en getUserStatus for at få samtlige loanId's, før selve fornyelserne kan sendes til biblioteket. I givet fald er det ændring at openUserStatus der skal laves før det kan blive en mulighed for DÅP.

**Comment by fvsdbc** [comment]
Har gjort feltet obligatorisk i swagger

**Comment by BettinaAndersen** [comment]
Testet ok. Godkendelse af @DDBdrift mangler
