### ISSUE TITLE
Overblik over brugen af DÅP

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#806]
Vi skal have et bedre overblik over hvem der benytter hvilke services på DÅP. Ved hver request sendes en token. Vi burde således kunne logge brugen.

Formålet er bedre at kunne prioritere og kommunikere i forhold til fejlrettelser, versions-skifte og lign.

**Comment by rasmuserik** [comment]
Har lavet et simpelt script, der udtrækker informationerne fra Elk'en. Hvis det skal give resultater pænt / live, afventer det #808 (hvilket er blocked indtil i morgen), hvorefter skal det tilpasses så søgningerne mod elk'en er fornuftige. Spørgsmålet er også hvor finpoleret resultatet skal være (hvorfor #810 stadigt er åben). Det foreløbige resultat fra scriptet, baseret på brugsdata siden 1/10:

Endpoints, ordered by usage:

1. work 2.0.0
1. work 1.0.0
1. recommend 1.0.0
1. suggest 1.0.0
1. search 1.0.0
1. suggest 2.0.0
1. availability 1.0.0
1. user 2.0.0
1. search 2.0.0
1. news 2.0.0
1. events 2.0.0
1. recommend 2.0.0
1. libraries 1.0.0
1. order 2.0.0
1. libraries 2.0.0
1. order 1.0.0
1. library 2.0.0
1. renew 2.0.0
1. facets 1.0.0
1. availability 2.0.0
1. user 1.0.0
1. news 1.0.0
1. events 1.0.0
1. rank 1.0.0
1. facets 2.0.0

ClientIds, ordered by usage:

1. 6a5f114a-XXX-XXX-XXX-XXXXXXXXXXXX
1. 7cf83ae2-XXX-XXX-XXX-XXXXXXXXXXXX
1. df669374-XXX-XXX-XXX-XXXXXXXXXXXX
1. acd5687a-XXX-XXX-XXX-XXXXXXXXXXXX
1. d171609c-XXX-XXX-XXX-XXXXXXXXXXXX
1. 24e1e74e-XXX-XXX-XXX-XXXXXXXXXXXX
1. 833b8ca4-XXX-XXX-XXX-XXXXXXXXXXXX
1. a36227da-XXX-XXX-XXX-XXXXXXXXXXXX
1. fb64f403-XXX-XXX-XXX-XXXXXXXXXXXX
1. d3c8575c-XXX-XXX-XXX-XXXXXXXXXXXX
1. e3dcf1fd-XXX-XXX-XXX-XXXXXXXXXXXX
1. 03ff1723-XXX-XXX-XXX-XXXXXXXXXXXX
1. 0e74de28-XXX-XXX-XXX-XXXXXXXXXXXX
1. 5acf3bba-XXX-XXX-XXX-XXXXXXXXXXXX
1. d814b5f3-XXX-XXX-XXX-XXXXXXXXXXXX
1. 29191e42-XXX-XXX-XXX-XXXXXXXXXXXX
1. c42bc501-XXX-XXX-XXX-XXXXXXXXXXXX
1. 25255a72-XXX-XXX-XXX-XXXXXXXXXXXX
1. 2e6c9855-XXX-XXX-XXX-XXXXXXXXXXXX
1. 637be8fb-XXX-XXX-XXX-XXXXXXXXXXXX
1. 81bd3d71-XXX-XXX-XXX-XXXXXXXXXXXX
1. 6cb7d283-XXX-XXX-XXX-XXXXXXXXXXXX
1. 7ba9f5b9-XXX-XXX-XXX-XXXXXXXXXXXX
1. 72aac357-XXX-XXX-XXX-XXXXXXXXXXXX
1. 063e46b1-XXX-XXX-XXX-XXXXXXXXXXXX
1. 83a8d2ba-XXX-XXX-XXX-XXXXXXXXXXXX

**Comment by BettinaAndersen** [comment]
Lukkes, da kun #810 er åben - og håndteres separat.
