### ISSUE TITLE
Sikr at DÅP logger de data vi skal bruge til statistik/overblik

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#809]
Endpoint etc. er allerede logget ifbm. GET/POST requests, men måske mangler de i loggen for websockets. Og hvor finkornet har vi brug for det. Evt. tilføj log af performance samtidigt.

- [x] tilføj clientId + timings til log i v1 for transformer endpoint kald
- [x] tilføj clientId + timings til log i v2 for transformer endpoint kald
- [x] tilføj clientId + timings til log i v3 for transformer endpoint kald

**Comment by rasmuserik** [comment]
Alle kald til transformer bliver logget [herfra](https://github.com/DBCDK/serviceprovider/blob/c88d4cc70ed6605e1b92352489754158a180308d/src/provider/caller.js#L162), da vi har loglevel DEBUG enabled. Kan findes ved at filtrere på `msg ≡ "transformer"`.

Community servicen er muligvis ikke implementeret som en transformer, så men disse kald kan findes i loggen via `accessLog` events.

Overblik over clientIds kan findes via loggen fra smaug.

**Comment by rasmuserik** [comment]
Reopen'er denne, da der ønskes en sammenhæng mellem endpoints og clientId, hvilket ikke er logget i nuværende udgave.

**Comment by rasmuserik** [comment]
clientId bliver ikke logget på nuværende tidspunkt, - det ser ud til at årsagen er an konfigurationen fra smaug har ændret sig. Opdaterer nu serviceprovideren v1, v2 og v3, så de bruger den nye sti i config.

**Comment by rasmuserik** [comment]
Så burde det være rettet. Afventer dog at det er rullet ud, og vi kan se resultatet i elk'en, da det afhænger af produktionskonfiguration.

**Comment by KiraH** [comment]
clientID kommer nu med ud i elk'en.
