### ISSUE TITLE
/search/search fejl ved tom parameter fields

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#833]
Hvis parametren `fields` er tom

```
curl -X GET \
  'https://openplatform.dbc.dk/v2/search?access_token={SLETTET}&q=nisse&fields='
```
fås svaret:
```
{
  "statusCode": 500,
  "error": "key '' is unknown"
}
```
Alle nøgler er kendte, men værdien af `fields` er tom. Bør værdien være obligatorisk, HVIS nøglen anvendes?

**Comment by rasmuserik** [comment]
Det kan være at jeg tager fejl, men i mine øjne, som udvikler, er dette forventet opførsel: _`fields` er ikke tom, men har værdien den tomme streng_. Fields bruges til, at vælge hvilke felter/nøgler i resultat-objekterne man ønsker at få tilbage (og den tomme streng er en mulig nøgle i JSON objekter). Den Åbne Platform validerer om den ønskede nøgle er et muligt felt i resultat-objektet, og giver en fejlmelding om at den ikke kender nøglen `''`. Jeg vil også antage, at den give samme fejlmeddelse i `search`-endpointet, hvis man sætter fields til andre strenge, som heller ikke er i den bibliografiske datamodel.

**Comment by DDBdrift** [comment]
Et godt datalogisk synspunkt! :-D
Men fejlmeddelelsen bør i alt fald være mere præcis:  `Value is empty or unknown in "Fields"`
I princippet er det faktisk ikke en fejl, da man (i teorien) kunne ønske at få et tomt svar retur.

**Comment by KiraH** [comment]
testet OK
