### ISSUE TITLE
Biblioteksspecifik login virker ikke med ISIL nr

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#834]
## brugerspecifikt login 
Man kan logge på med:
`username=$USER_ID@LIBRARY_ID&amp;password=$PINCODE`

Hvor `LIBRARY_ID` kan være enten biblioteksnr eller ISIL nr. 

## biblioteksspecifikt login 
Man burde kunne logge på med:
`username=@$LIBRARY_ID&amp;password=@$LIBRARY_ID`

Det lykkes KUN hvis $LIBRARY_ID erstattes med biblioteksnr.. Ved ISIL nr fås fejlmeddelelsen:

> "User credentials are invalid"

**OBS!** Der mangler et `$` i eksemplet foran `LIBRARY_ID` i brugerspecifik login

**Comment by BettinaAndersen** [comment]
Fejl observeret med Roskilde bibliotek

**Comment by rasmuserik** [comment]
Har lavet en pull-request dbcdk/smaug#201. Så snart den bliver merget ind, og deployet, burde det løse problemet. Det er i smaug (loginsystemet) og ikke serviceprovideren det skal rettes.

Har også tilføjet det manglende `$` i dokumentationen i serviceprovideren (v3).

**Comment by KiraH** [comment]
Testet OK og smaug rullet ud i produktion.
