### ISSUE TITLE
culr kald til oauth har forkert syntaks (Autentificeret)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#836]
Der er en fejl i logikken på argumenterne til `username` og `password`.
I `Anonym` og `Biblioteksspecifik` er logikken:
`${USER_ID}@${LIBRARY_ID}` og `password=${PINCODE}@${LIBRARY_ID}`
I `Autentificeret` er logikken:
`${USER_ID}@${LIBRARY_ID}` og `password=${PINCODE}` altså UDEN `@${LIBRARY_ID}`
Dette bør været ens
`${USER_ID}@${LIBRARY_ID}` og `password=${PINCODE}@${LIBRARY_ID}`

Dvs  Autentificeret
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d 'grant_type=password&amp;username=$USER_ID@LIBRARY_ID&amp;password=$PINCODE'`
Burde være:
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d "grant_type=password&username=$USER_ID%40${LIBRARY_ID}&password=${PINCODE}%40${LIBRARY_ID}"`

**Comment by DDBdrift** [comment]
#837

**Comment by rasmuserik** [comment]
Hvis vi ændre logikken i authentificeringen så vi kræver LIBRARY_ID, vil det, så vidt jeg kan se, brække login med bruger for alle eksisterende klienter (da authentificeringen er generel/separat, og ikke knyttet til v3).

Logikken er så vidt jeg ved: at `password` er pinkoden, hvis der er brug for en pinkode, og ellers blot det samme som `username`.

Problemet her er vel, at logikken for username/password ikke er godt nok dokumenteret (i.e. #837), så det skal løses ved at rette dokumentationen, frem for måden at logge ind på?

**Comment by DDBdrift** [comment]
Dybest set er det manglende logik i selve login. Hvis man skal tilføje "@libraryID" i nogle kald, så bør det være med i ALLE

**Comment by DDBdrift** [comment]
Leave a comment

**Comment by rasmuserik** [comment]
@DDBdrift så vidt jeg kan se:

- "@libraryid" er tilføjet som en del af brugernavnet *i ALLE* kald.
- Det bliver ikke *tilføjet* andre steder *i nogle kald*. 

For brugere uden `password` (anonyme brugere) sættes `password` til det samme som `username`, da det vistnok ikke kan være tomt ifølge OAuth2-standarden. (hvilket er årsagen til, at det i visse tilfælde indeholder et libraryid).

At man skulle tilføje et `@libraryid` til et `password` er, så vidt jeg kan se en misforståelse. Så det, der i mine øjne er vigtigt her, er at få rettet dokumentationen, så denne misforståelse ikke forekommer igen.

Jeg kan godt gå ind og ændre hele logikken / koden for login, og kræve, at kodeord består af kode og biblioteksid. Umiddelbart ser det ud til, at **det vil brække alle eksisterende klienters login-flow**, - og det er i mine øjne også brug af resourcer på, at forringe vores login-løsning. ***Er du HELT SIKKER på, at det er det sidstnævnte, som I ønsker?***

**Comment by DDBdrift** [comment]
Til OpenPlatform er der tre mulige kombinationer:

| Type |  Oauth2 argumenter |
|---|---|
| Authentified      | &Agency={ISIL}&username={CPR}&password={PIN} |
| Library specific   | &Agency={ISIL}&username=&password= |
| Annonymous      |  &Agency=&username=&password= |
 
Når jeg kigger på logikken som beskrevet på https://www.oauth.com/oauth2-servers/access-tokens/password-grant/
så burde kaldet til oauth være:

`grant_type=password&username=user@example.com&password=1234luggage`

eller

`grant_type=password&username={CPR}@{ISIL}&password={PIN}`

Hvis oauth2 ikke kan acceptere et tomt pasord, så bør det håndteres i laget imellem OpenPlatform og Oauth. Eksempel vis ved at indsætte et @.
Når den slags er nødvendigt er det i realiteten fordi denne metode perverterer oauth.
Min pointe er at kaldet SKAL være ensartet og stringent. Enten tilføjer man et @ til pin eller også gør man ikke. "Nogen gange" er ikke et acceptabelt svar.

**Comment by BettinaAndersen** [comment]
Lad os vende denne til vores møde den 9. april

**Comment by BettinaAndersen** [comment]
Løses ved dokumentation i #837

**Comment by DDBdrift** [comment]
Det var en god rettelse, men må jeg foreslå, at tage den et skridt videre:

| Type	| Bibliotek	| Lånernummer	| ${USERNAME}	| ${PASSWORD}	| Kommentar| 
|  --- |  --- |  --- |  --- |  --- | --- |
| Brugerlogin - Låner på bibliotek	| Specifikt bibliotek, fx Københavns Biblioteker (agency DK-710100)	| lånernummer, eksempelvis: 12345678	| `12345678@710100`	| `1234`	| Brugerens faktiske pin-kode, eksempelvis "1234"| 
| Bibliotekslogin - uden låner	| Specifikt bibliotek, fx Københavns Biblioteker (agency DK-710100)	| Ingen bruger / lånernummer	| `@710100`	| `@710100`	| Der er ingen pinkode, så derfor er ${PASSWORD} det samme som ${USERNAME}: "@"| 
| Annonym - ingen låner eller bibliotek angivet	| Ingen bibliotek	| Ingen bruger / lånernummer	| `@`	| `@`	| Der er ingen pinkode, så derfor er ${PASSWORD} det samme som ${USERNAME}: "@"|

**Comment by rasmuserik** [comment]
Tak, - har indføjet det i dokumentationen nu, - skulle være på staging om lidt :)

**Comment by DDBdrift** [comment]
Herligt!
