### ISSUE TITLE
culr kald til oauth har forkert syntaks i dokumentationen

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#837]
https://openplatform.dbc.dk/v2/

# Generelle rettelser:
- `&amp;` rettes til `&`
- variable ændres fra $VAR til ${VAR}
- Enkelt pling `'` ændres til dobbelt `"` aht expansion af variable
- `@` ændres til `%40` for at undgå expansion

# Specifikke rettelser

## Anonym
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d 'grant_type=password&amp;username=@&amp;password=@'`
Burde være:
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d "grant_type=password&username=%40&password=%40"

## Biblioteksspecifik
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d 'grant_type=password&amp;username=@$LIBRARY_ID&amp;password=@$LIBRARY_ID'`
burde være:
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d "grant_type=password&username=%40${LIBRARY_ID}&password=%40${LIBRARY_ID}"`

`LIBRARY_ID er et biblioteks ISIL nummer f.eks. 710100 for København.`
rettes til:
`LIBRARY_ID er et biblioteks ISIL nummer ("DK-710100") eller et simpelt biblioteksnummer ("710100")`

## Autentificeret
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d 'grant_type=password&amp;username=$USER_ID@LIBRARY_ID&amp;password=$PINCODE'`
Burde være:
`curl --user "$CLIENT_ID":"$CLIENT_SECRET" -X POST https://auth.dbc.dk/oauth/token -d "grant_type=password&username=$USER_ID%40${LIBRARY_ID}&password=${PINCODE}%40${LIBRARY_ID}"`

OBS! Tilføjelsen af `@${LIBRARY_ID}` til Autentificeret kræver en rettelse (#836)

**Comment by DDBdrift** [comment]
#836

**Comment by rasmuserik** [comment]
Afventer afklaring af #836
