### ISSUE TITLE
Forbedring af de automatisk genererede tests

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#841]
Øvrige dele af #818 som ikke er med i sprint 47-48.

- [x] undgå duplikeret json data i test
- [x] tilføj tydelig warning om at dette er en autogenereret fil, som kan regenereres i stedet for at editeres
- [x] regenerer fra metadata i testfil, frem for liste.
- [x] sikr at autogenererede test cases bliver regenereret regelmæssigt (så de ikke kommer ud af sync med de underliggende services)
- [x] Opdater dokumentation om test i `README.md`
- [x] reset request time i mock-data, så regenerering ikke nødvendigvis medfører stor diff
- [x] navngiv automatisk generererede unit tests, så de let kan genkendes ud fra navnet

**Comment by KiraH** [comment]
OK
