### ISSUE TITLE
/recommend - struktur på returdata

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#854]
Forventer:
```
Recommendation {
creator (string, optional),
fromPid (string, optional),
pid (string, optional),
title (string, optional),
weight (integer, optional)
}
```

Men får
```
{
    "statusCode": 200,
    "data": [
        {
            "creator": [ "Rune Fleischer"    ],
            "val": 0.2737536614150203,
            "title": [ "Otto på festival"   ],
            "pid": [  "870970-basis:50936163"   ]
        },
        {

```
Er "val" og "weight" indentiske? Hvor er "fromPid" ?

**Comment by DDBdrift** [comment]
#770

**Comment by rasmuserik** [comment]
Den Åbne Platform giver forøjeblikket blot resultatet fra recommenderen videre og pakker felter ind i arrays som ønsket i #770.

Mit gæt er at dokumentationen/specifikationen er ude af sync med recommenderen, og jeg laver et pull request på at opdatere spec'en.  @DDBdrift: vil dette løse issuet?

`val` er så vidt jeg ved `weight`, - og `fromPid` vil jeg gætte på er forsvundet vil en opdatering af recommenderen. (`fromPid` virker i mine øjne som en implementationsdetalje, så derfor ikke underligt hvis den forsvinder ved en ny implementation, - burde måske ikke være eksponeret til at starte med)

Har  også set at mål for v.3  (#852),  indeholder ny recommender, så det kan være at der  kommer ændringer her.

Note til mig selv: tjek at dette issue også er fanget som fejl i loggen.

**Comment by rasmuserik** [comment]
Så er specifikationen opdateret.

**Comment by DDBdrift** [comment]
Er den klar til test? Kan ikke se noget eksempel i dokumentation

**Comment by rasmuserik** [comment]
I version 3, har vi lige straks et nyt recommender-endpoint, og denne omhandler struktur af de gamle data, som så ikke eksisterer mere, så lukker denne.
