### ISSUE TITLE
Fejl ved /status/user (opdatér spec)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#863]
data indeholder en liste:
```
{
  "statusCode": 200,
  "data": {
    "id": "Hp3NLdsxOKC8Ow/Y+qdxyk1UQcMSxWY/",
    "name": "...",
```
Burde være:
```
{
  "statusCode": 200,
  "data": [ {
    "id": "Hp3NLdsxOKC8Ow/Y+qdxyk1UQcMSxWY/",
    "name": "...",
```

**Comment by rasmuserik** [comment]
Jeg kan ikke lige forstå dette issue, - hvor indeholder `/user` en liste?

**Comment by rasmuserik** [comment]
Ah, tror at jeg forstår issuet nu: nej, `data` i response-objektet _indeholder ikke altid en liste_. `data` indeholder svaret på forespørgslen, som ofte er en liste (ved søgninger etc.). Man er kun logget ind som én bruger ad gangen, så derfor returnerer `/user` endpointet blot et bruger-objekt. Så vidt jeg ved har det aldrig været intentionen at `/user` skulle returnere flere brugere. Men det kan sagtens være, at jeg tager fejl?

**Comment by DDBdrift** [comment]
Jeg tænkte, at det var samme problem som i #849

**Comment by rasmuserik** [comment]
... så denne kan vel lukkes, eller ?

**Comment by DDBdrift** [comment]
Du har ret: én bruger ad gangen
