### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#867]
which were tested by api-test while it was still used. (part of #820)

- [x] websocket transport
- [x] GET transport
- [x] POST transport
- [ ] Look at coverage, and add obvious candidates.

**Comment by rasmuserik** [comment]
Note start evt. på at implementere #874, da det vil gøre det lettere at test ovenstående.

**Comment by KiraH** [comment]
lukker denne.
