### ISSUE TITLE
HowRU-Endpoint

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#874]
Nyt endpoint som returnerer version og solnedgang på DÅP og versions-nr for underliggende services til klienten. Hvis status på underliggende service er givet, så gives det med.

Checklist (added/edited):
- [x] opensearch
- [x] openholdingstatus
- [x] openorder
- [x] opensearch
- [x] openuserstatus
- [x] moreinfo
- [x] ddbcms (currently only url, - to show it is there, - it does not seem to have version nor status, or does it?)
- [x] endOfServiceDate ("solnedgang")
- [x] recommend
- [x] suggest (currently only url, as suggest is still missing).

**Comment by rasmuserik** [comment]
note: endpointet kaldes `/status`

**Comment by rasmuserik** [comment]
Solnedgang?

**Comment by KiraH** [comment]
Kan du ikke smide en url til hvor jeg burde kunne tilgå endpointet, hverken https://openplatform-stg.dbc.dk/status eller https://openplatform-stg.dbc.dk/v2/status kommer med noget brugbart.

På vores andre services hedder endpointet howru, så umiddelbart ville det være rart hvis dette endpoint hed det samme.

**Comment by KiraH** [comment]
testet OK
