### ISSUE TITLE
Brønd 3.0 lukkes 

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#882]
Det er meldt ud af Brønd 3.0 lukkes fra 1. januar i år. Derfor skal der ryddes op i konfigurationer, dokumentation og andet relateret til Brønd 3.0. Dette skal gøres inden 1. februar.

**Comment by vibjerg** [comment]
Alle klienter er set igennem, og dem som refererede til brønd 3.0 er blevet opgraderet.
