### ISSUE TITLE
/order hænger ved forkert bibliotek

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#889]
i.e. hvis `library`  er en forkert værdi, kommer der ikke noget svar fra order-endpointet.

**Comment by BettinaAndersen** [comment]
Hvis det er den underliggende service der fejler, skal denne sende korrekt fejlbesked tilbage.

**Comment by rasmuserik** [comment]
Dette issue dækker, at dokumentere hvordan issuet reproduceres, og oprette issue på den undeliggende service.

**Comment by rasmuserik** [comment]
Har forsøgt at reproducere det, - og det lykkedes ikke :(

Til gengæld fik jeg sendt en bestilling,
til en filial i en anden kommune,
end dér hvor jeg var logget ind,
og fik "ok" tilbage,
så er spændt på hvad det medfører...
@BettinaAndersen: Er det et issue, 
der skal rejses i openorder?

Ellers tænker jeg bare at vi lukker dette issue?
