### ISSUE TITLE
/recommend/rank - val er skiftevis tabel og decimaltal

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#896]
Har prøvet gentagende kald til:

> https://openplatform-stg.dbc.dk/v3/rank?access_token=SLETTET&pretty=true&timings=true&pids=%5B%22870970-basis:28511663%22,%22870970-basis:28902239%22%5D&like=%5B%22870970-basis:45488713%22,%22870970-basis:28643713%22%5D

Og får skiftevis:

```
      "creator": [
        "Jussi Adler-Olsen"
      ],
      "val": 62.798478002209706,
      "ctkey": [
        "Journal_64_:_krimithriller::Jussi_Adler-Olsen"
      ], 
```

og

```
      "creator": [
        "Jussi Adler-Olsen"
      ],
      "val": [
        62.798478002209706
      ],
      "ctkey": [
        "Journal_64_:_krimithriller::Jussi_Adler-Olsen"
      ], 
```

**Comment by KiraH** [comment]
Der var en typo i kommandoen til genstart af servicen på den ene server, så den ikke blev genstartet. Det bevirkede at den ene server kørte videre på den gamle kode. Det er nu rettet.

**Comment by DDBdrift** [comment]
Ser ud til at svare konsistent
