### ISSUE TITLE
Swagger fejl: "malformed or unreadable swagger supplied" (Staging v.3)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#898]
Swagger melder fejl på dokumentationssiden: 
https://openplatform-stg.dbc.dk/v3/

[ base url: /v3 , api version: 3.0.0 ]

Error {...}

> {"messages":["malformed or unreadable swagger supplied"]}

**Comment by rasmuserik** [comment]
Muligvis en fejl i den gamle udgave af swagger, - testede swaggerfilen (med værktøj der kører lokalt), uden at den fandt nogen fejl, - og har nu opgraderet swagger-ui, hvor jeg ej heller kan se fejlen.

**Comment by DDBdrift** [comment]
Hovsi - der er ikke nogen validering. Eller kommer der kun en meddelelse ved fejl?
Afsnittet "Tokens" er røget helt ned i bunden. Bør flyttes op under beskrivelsen i toppen

**Comment by rasmuserik** [comment]
Det ser ud til, at den seneste udgave af swagger-grænsefladen, ikke har et valideringsikon, i modsætning til den tidligere udgaver.

Til gengæld validerer vi swagger-filen, ved hver eneste ændring af serviceprovideren, i.e. <https://travis-ci.org/DBCDK/serviceprovider/builds/361539875#L2857> og burde få en fejl allerede under udviklingen, hvis den ikke validerer. (her bruger vi <https://npmjs.com/swagger> `validate` funktionen)

Konklusionen foreløbigt er, at hverken seneste udgave af `swagger-ui` eller af `swagger` npm-pakken fanger at der skulle være fejl i swagger-specifikationen :( - begge dele er de officielle værktøj fra swagger.

Hmm, - har lige prøvet at køre swagger-filen, gennem andre swagger-validerings-værktøj, som finder fejl. Der er også forskellige versioner af swagger-api-specifikationen.

Jeg dykker dybere ned i dette, og prøver, at finde ud af hvad der går galt.

----

Afsnittet "tokens" røg ned i bunden, da da jeg vurderede at API dokumentationen er hyppigere læst / vigtigere, - jeg flytter den op i beskrivelsen i toppen igen.

**Comment by rasmuserik** [comment]
`swagger-tools validate` ser umiddelbart heller ikke ud til at komme med valideringsfejl.
Men swagger-parser valideringen kommer med nogle fejl, - kigger nu på hvordan disse integreres i den automatiske test.

**Comment by rasmuserik** [comment]
Kan se at valideringsfejlen ligger i dele af community-servicen, så vil gerne afklare hvad status er med denne, inden jeg dykker mere ned i det. 

Har lavet en branch, der opdaterer dokumentationen, og kører tre valideringer af swagger-filen, i den automatiske test ved hver pull-request (hvoraf 2 er ok og en fejler forøjeblikket).

(heldigvis giver swagger-parser betydeligt mere sigende fejlbeskeder, end swagger-ui-v2-webservicen)

**Comment by DDBdrift** [comment]
Vi har community-servicen på dagsordenen d. 9/4. So hold your horses
