### ISSUE TITLE
Begin specifying the API with swagger

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#9]
Tasks:

- [x] further brainstorm/notes on overall api-design (in doc/api-design.md)
    - [x] identify different categories of functionality
    - [x] go through mobilsoeg-api and biblo-functionality
- [x] figure out how we specify it best in swagger
- [x] start writing first draft of api-spec

**Comment by adamtulinius** [comment]
Considering the wording, this task must be done.
