### ISSUE TITLE
håndtering af "Cannot read record" poster fra OpenSearch

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#900]
Hvis Opensearch får en fejl når den forsøger at hente en post, vil den skrive "Cannot read record" i postens titel. Se eksempel nedenfor.

Disse poster skal DÅP kunne håndtere.

{
"collection": {
"resultPosition": {
"$": "4"
},
"numberOfObjects": {
"$": "1"
},
"object": [
{
"record": {
"title": [
{
"$": "Cannot read record:",
"@": "dc"
}
],
"@": "dkabm"
},
"identifier": null,
"formatsAvailable": {
"format": [
{
"$": "dkabm"
}
]
},
"objectsAvailable": null
}
]
},
"formattedCollection": {
"briefDisplay": {
"manifestation": [
{
"accessType": {
"$": "physical"
},
"creator": {
"$": "Hardcore Superstar"
},
"fedoraPid": {
"$": "870970-basis:23808919"
},
"identifier": null,
"title": {
"$": "Thank you (for letting us be ourselves)"
},
"titleFull": {
"$": "Thank you (for letting us be ourselves)"
},
"type": {
"$": "Cd (musik)"
},
"workType": {
"$": "music"
}}]}}},

**Comment by BettinaAndersen** [comment]
Relateret til https://github.com/DBCDK/biblo/issues/760

**Comment by rasmuserik** [comment]
Er der et eksempel på en søgning, der returnere dette (inkl. søgeprofil etc.)?

(reassign derefter til mig, så kigger jeg på den :wink: )

**Comment by mtni** [comment]
DÅP skal logge hvis identifier er null.

**Comment by BettinaAndersen** [comment]
Ikke pt. et issue. Bør håndteres af OS
