### ISSUE TITLE
Performancestatistik i /status endpoint

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#905]
Udtrækkes fra ELK'en.

**Comment by rasmuserik** [comment]
NB: endpointet der udtrækker performance-statistik er implementeret, men der er endnu ikke åbnet op for adgangen til performance-statistikken, så det kan ikke testes før end #906 og #808 er løste

**Comment by KiraH** [comment]
lukker denne, så må vi teste når de andre er færdige.

**Comment by DDBdrift** [comment]
Mener ikke at det har opsættende virkning på relase af v.3 prod

**Comment by rasmuserik** [comment]
Var `fixed` i koden (virkede når men kørte den her) på den gamle udgave af log-infrastrukturen, men denne har ændret sig blandt andet ifbm. GDPR, - håndteres i #935 

Har rykket omkring den underliggende infrastruktur tidligere i denne uge, og har en aftale om at følge op i næste uge.
