### ISSUE TITLE
Åbnes op for Elk'en

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#906]
For at kunne udtrække perfomance-målinger til Status-endpoint, skal der åbnes op for adgang til Elk'en. 
Relateret til #905

**Comment by rasmuserik** [comment]
Har lige tjekket loggen, og staging (og dermed nok også prod) ser ikke ud til at have adgang til elk'en, - jeg tror ikke at jeg har adgang til at åbne op.

**Comment by rasmuserik** [comment]
Har testet, at der er åbnet op, - og performance-statistikken virker nu på staging :)

(Får kun noget ud i de uger hvor vi faktisk har data, eksempelvis uge 15: https://openplatform-stg.dbc.dk/v3/status?week=2018-W15&access_token=_INDSÆT_TOKEN_HER)
