### ISSUE TITLE
Manglende brugsstatistik i Kibana

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#907]
Det ser stadig ikke ud til at Kibana viser nogen brugsstatistik. Se eksempelvis: http://elk.dbc.dk:5601/#/visualize/create?indexPattern=%5Bprod_ux-%5DGGGG.WW&type=histogram&_a=(filters:!((meta:(disabled:!f,index:%5Bprod_ux-%5DGGGG.WW,key:app,negate:!f,value:serviceprovider),query:(match:(app:(query:serviceprovider,type:phrase)))),(meta:(disabled:!f,index:%5Bprod_ux-%5DGGGG.WW,key:msg,negate:!f,value:transformer-done),query:(match:(msg:(query:transformer-done,type:phrase))))),linked:!f,query:(query_string:(analyze_wildcard:!t,query:'*')),vis:(aggs:!((id:'3',params:(field:name,orderBy:'2',size:20),schema:segment,type:terms),(id:'2',schema:metric,type:count)),type:histogram))&_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:'2018-03-06T23:00:00.000Z',mode:absolute,to:'2018-03-13T13:14:02.809Z'))

Kira: Et godt sted at starte ville være at se på hvordan loggen ser ud i syslog på serveren, så kan vi se om det er loggen der er ændret eller der sker noget på vej til Kibana.

**Comment by rasmuserik** [comment]
@KiraH: Det ser ud til at data ligger uparset i syslogall, men ikke bliver parset korrekt ind i prod_ux.

**Comment by BettinaAndersen** [comment]
Lukkes, da problemet ikke længere er relevant.
