### ISSUE TITLE
Trunkeret svar fra /libraries (timings)

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#915]
Problemet er ikke konsisten, men periodisk mangler timings fra svaret:

> https://openplatform-stg.dbc.dk/v3/libraries?
> access_token=SLETTET&pretty=true&timings=true&agencyIds=[%22725300%22]&branchIds=[%22725300%22]

[libraries.json.txt](https://github.com/DBCDK/serviceprovider/files/1832516/libraries.json.txt)

**Comment by rasmuserik** [comment]
Mit bud er, at de manglende timings skyldes, at endpointet igangsætter en opdatering af den cachede liste af biblioteker, - som ikke er afsluttet når den giver resultatet, - og timings derfor ikke er afklaret. Dette burde løses ved at cache-opdateringen flyttes til et andet timeslice, hvilket er gjort i #919

**Comment by DDBdrift** [comment]
Kan ikke genskabe fejlen.
