### ISSUE TITLE
availability: orderPossible defaults to true.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#922]
orderPossible is set to true by default in the result, - this includes result for every existing (and non-existing) material, if underlying services fails. openorder-check-order-policy does not seem to handle errors that well.

**Comment by mtni** [comment]
Hvis servicen fejler, skal der sendes en fejlbesked - ikke "true"-tilbage.

**Comment by KiraH** [comment]
OK, ikke testet i brugergrænsefladen.
