### ISSUE TITLE
tilretning af konfiguration

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#925]
Konfigurationen skal rettes så ny recommender og suggest bruges.

Desuden skal der tilføjes serviceurl til ekl'en til performancemålinger.

**Comment by KiraH** [comment]
Nye url'er tilføjet til konfig, i første omgang til staging.

**Comment by rasmuserik** [comment]
Har testet, og nu timer requests mod recommend/suggest ud, hvilket tyder på et firewall-issue.

**Comment by KiraH** [comment]
OK, jeg opretter en sag på at få åbnet.

**Comment by rasmuserik** [comment]
@rasmuserik test om suggest/recommend virker

**Comment by rasmuserik** [comment]
suggest/recommend virker :)
ELKen håndteres i andet issue #906 .
