### ISSUE TITLE
Forbedringer af Community Service (analyse)

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#929]
Der skal laves en beskrivelse / forslag til hvordan Community Servicen kan generaliseres/forbedres ud fra faktiske brugsscenarier, eksempelvis, at den kunne levere backend-funktionalitet for

- quiz-funktionalitet
- lister (der er allerede bygget lignende funktionalitet oven på den underliggende community service i contant-first-projektet)
- events og nyheder for biblioteket (måske vil den kunne erstatte cmscontent / ddbcms:"push to mongo")

dette vil også berøre adgangsstyring, samt beskrivelse af den underliggende Community Service.

Udkast

- hovedtekst
    - [x] motivation
    - [x] forslag
- bilag
    - [x] forslag løser brugsscenarier
    - [x] sikkerhed og adgangsstyring
    - [x] beskrivelse af underliggende community service
    - [ ] tekniske noter

**Comment by BettinaAndersen** [comment]
Dokument leveret til DDB
