### ISSUE TITLE
/libraries svarer: Cannot read property 'userParameter' of undefined

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#943]
> curl -X GET "https://openplatform-stg.dbc.dk/v3/libraries?access_token=SLETTET&pretty=true&timings=true&agencyIds=%5B%22DK-726500%22%5D" -H "accept: application/json"
svarer
```json
{
  "statusCode": 500,
  "error": "TypeError: Cannot read property 'userParameter' of undefined"
}
```

**Comment by rasmuserik** [comment]
Det ser ud til, at det skyldes at `serviceResponse` mangler i det svar som vi får fra openagency. Et gæt kunne være at det måske skyldes `DK-` i agency-id som vi giver videre. Sætter den på min backlog.

**Comment by rasmuserik** [comment]
Forekommer fejlen stadigt, - jeg kan ikke reproducere den.

**Comment by DDBdrift** [comment]
Kan ikke reproducere heller
