### ISSUE TITLE
sporadic CoverUrls error

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#945]
I have gotten a few errors like:

```
CoverUrls could not be fetched. Server probably unavailable. Try request again without coverUrls.
```

While fetching covers for content-first. Cannot be consistently reproduced. May be an issue with the underlying service. Added as an issue here, as a reminder to look more into this at some point.

**Comment by BettinaAndersen** [comment]
Sandsynligvis samme fejl, som bliver synlig her https://github.com/DBCDK/content-first/issues/467

Er det MoreInfo eller Dåp, som giver fejlen?

**Comment by rasmuserik** [comment]
Det ser ud til at være moreinfo, - kan udvide logningen i dåp så vi kan se flere detaljer.

**Comment by rasmuserik** [comment]
#954 har tilføjet mere logning, så vi kan se mere om hvad der går galt.
