### ISSUE TITLE
ensretning af logning

### ISSUE THREAD

**Issue by KiraH** [DBCDK/serviceprovider#957]
logning skal ensrettes så alle services der logger til sammen namespace benytter samme type til det samme index.

Der er problemer med:
Den oftest benyttede type står først i parantes efter.

params
params.userId(text og long)
request
user 
"params.campaignId" 
response 
port(long og text)
pid(long og text)
session.passport.user.profile.profile.created(date og text) 
session.passport.user.profile.profile.lastUpdated(date og text)
version(long og text)

**Comment by rasmuserik** [comment]
@KiraH Jeg tænker i første omgang at sikre at det som vi skal bruge for performance-status bliver logget så det matcher, - har ikke helt overblikket over alle services, og hvad der skal rettes, så vi må nok lige koordinere undervejs, - har derfor assignet os begge.

**Comment by rasmuserik** [comment]
Er deployet, og har testet at det virker.

Dette er at vores logning af kørsel af de enkelte transformers er ensrettet, hvilket er det vi skal bruge til performancestatistik. Det er ikke en generel ensretning af alle vores log på tværs af alle produkter, men blot det der var kritisk i forhold til statistik.

Jeg unassigner mig, da det konkrete problem er løst. (måske kan den lukkes, måske skal der gøres mere, @KiraH ?)

**Comment by KiraH** [comment]
Lad os lukke denne og så løbende kontrollere om der stadig er noget der knækker loggen. Så må vi oprette nye issues hvis vi finder mere.
