### ISSUE TITLE
Availablity endpoint misfortolker holdingsResponse

### ISSUE THREAD

**Issue by fvsdbc** [DBCDK/serviceprovider#958]
Hvis brugerens bibliotek ikke har det ønskede materiale, svares tilbage med fx:

<holdingsResponse>
  <error>
    <pid>870970-basis:06205836</pid>
    <responderId>DK-710100</responderId>
    <errorMessage>item_not_found</errorMessage>
  </error>
</holdingsResponse>

hvilket leveres videre fra openHoldingsStatus.js med statusCode 500, hvilket så får availabilty.js til at returnere med unavailable: ....

Hvis error.errorMessage er "item_not_found", skal openHoldingsStatus istedet returnere data.willLend = 'false' og statusCode 200

**Comment by fvsdbc** [comment]
Måske kan det løses med at rette:

    if (body.error) {
      return {statusCode: 500, error: body.error[0].errorMessage.$};
    }
    body = body.responder;
    let data = {willLend: false};
til 
    let data = {willLend: false};
    if (body.error) {
      if (body.error[0].errorMessage.$ === 'item_not_found') {
        return {statusCode: 200, data: data};
      }
      return {statusCode: 500, error: body.error[0].errorMessage.$};
    }
    body = body.responder;

**Comment by rasmuserik** [comment]
Enig, det løser det, - har lavet pull request, inkl. test case, hvor resultat også kan ses.
