### ISSUE TITLE
Tilretning af config

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#967]
@kirah performance-urlen i config'en skal have tilføjet et `prod_ux-*/`, og jeg har vist ikke adgang til at gøre dette.

Når dette er gjort skal jeg rette `src/transformers/status.js` så det ikke indeholder config-workaround.

**Comment by KiraH** [comment]
jeg har nu tilføjet til config filerne i smaug, så kan du rette til og så kan vi rulle det ud.
