### ISSUE TITLE
Overblik over v1. og V2 klienter

### ISSUE THREAD

**Issue by BettinaAndersen** [DBCDK/serviceprovider#974]
Officielt lukker vi DÅP 1 og 2 den 15. august, men disse bruges stadig.

Vi har brug for en liste over aktive klienter på version 1 og 2, så de kan kontaktes for at få dem flyttet til version 3.

Aktive klienter skal være nogle som har benyttes V. 1 eller V2. inden for en uge. (ca.)

**Comment by KiraH** [comment]
Klienter der benytter v1 og v2 er identificeret. Jeg opretter issues på at få skiftet vores egne og vi giver besked til de eksterne om at de skal flytte til ny version.
