### ISSUE TITLE
configuration from Smaug should be cached

### ISSUE THREAD

**Issue by adamtulinius** [DBCDK/serviceprovider#98]
The cache should be short-lived, maybe 60s. It should still eliminate many lookups in Smaug.

**Comment by adamtulinius** [comment]
This test..:
`ab -n 10000 -c 10 -H "Authorization: Bearer qwerty" "http://localhost:8080/v0/suggest"`
.. currently results in SP performing ~1200 req/s with crude caching, compared to ~500 req/s when getting the context from smaug on all requests on my laptop.

**Comment by BettinaAndersen** [comment]
Relevans overskrevet
