### ISSUE TITLE
Søgning kan ikke indeholde komma, apostrof eller ampersand

### ISSUE THREAD

**Issue by DDBdrift** [DBCDK/serviceprovider#987]
Har forsøgt mig med at søge på title: "Den klarer jeg, Rasmus!"
Den kan findes i Roskilde på:
`https://www.roskildebib.dk/search/ting/ti%3D%22Den%20klarer%20jeg%2C%20Rasmus%21%22`

Jeg kan slå den op med:
```
https://openplatform.dbc.dk/v3/search?access_token=SLETTET&pretty=true&timings=true&q=ti=%22Den%20klarer%20jeg%20Rasmus%22&offset=0&limit=20&sort=rank_verification&fields=[%22titleFull%22,%20%22creator%22,%20%22pid%22,%20%22coverUrlThumbnail%22]
```
Hvilket giver
```
{
  "statusCode": 200,
  "data": [
    {
      "titleFull": [
        "\"Den klarer jeg, Rasmus!\""
      ],
      "creator": [
        "Ditte Ahm"
      ],
      "pid": [
        "870970-basis:07275595"
      ]
    }
  ],
  "timings": {
    "total": 834,
    "external": 817
  }
}
```
Men jeg kan ikke slå den op i /search med komma:
```
https://openplatform.dbc.dk/v3/search?access_token=SLETTET&pretty=true&timings=true&q=ti=%22Den%20klarer%20jeg%20Rasmus,%22&offset=0&limit=20&sort=rank_verification&fields=[%22titleFull%22,%20%22creator%22,%20%22pid%22,%20%22coverUrlThumbnail%22]
```
```
{
  "statusCode": 400,
  "error": "q is not of a type(s) string"
}
```

Af andre spændende titler er:
ti="Enhjørningen's hemmelighed" (Apostroph)
ti="& Gillian"  (Ampersant)

**Comment by rasmuserik** [comment]
Dette har så vidt jeg kan se ikke noget med søgning at gøre, men derimod hvorledes parametre gives med i en url. Hvis en url-parameter indeholder særlige tegn, bør den sættes i gåseøjne.

Hvis `,` optræder i en url-parameter, svarer det til, at det er en liste i stedet for en streng. Hvis du vil bruge komma, skal der sættes gåseøjne om strengen, i.e.: `q="ti=\"Den klarer jeg, Rasmus\""`. 

`&` bruges til at adskille forskellige url-parametre, og skal altid encodes som `%26` hvis det er en del af en url-parameter.

Umiddelbart kan jeg ikke se nogen årsag til at apostrof skulle fejle, - og når jeg prøver forespørgslen med apostrof her, så virker den fint, - også uden at parametren er sat i gåseøjne.

**Comment by DDBdrift** [comment]
Vi er nok ikke de eneste som falder i den fælde :¤)
Tilføjet i dokumentationen: https://danskernesdigitalebibliotek.github.io/OpenPlatform/endpoints/search#search
